namespace Winform4System.Forms.SystemManagement
{
    partial class AuditLogView
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarEditItem dateFrom, dateTo, userKeyword, actionCode, entityName, keyword;
        private DevExpress.XtraBars.BarButtonItem btnSearch, btnReload, btnExport;
        private DevExpress.XtraEditors.Repository.RepositoryItemDateEdit repositoryDateFrom, repositoryDateTo;
        private DevExpress.XtraEditors.Repository.RepositoryItemTextEdit repositoryUser, repositoryKeyword;
        private DevExpress.XtraEditors.Repository.RepositoryItemComboBox repositoryAction, repositoryEntity;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutGrid, layoutResult;
        private DevExpress.XtraGrid.GridControl gridAudit; private DevExpress.XtraGrid.Views.Grid.GridView gridViewAudit;
        private DevExpress.XtraEditors.LabelControl lblResult;
        private DevExpress.XtraGrid.Columns.GridColumn colCreatedAt, colUserId, colUserName, colAttemptedUser, colAction, colEntity, colEntityId, colDescription, colMachine, colIpAddress, colCorrelationId;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar();
            dateFrom = new DevExpress.XtraBars.BarEditItem(); dateTo = new DevExpress.XtraBars.BarEditItem(); userKeyword = new DevExpress.XtraBars.BarEditItem(); actionCode = new DevExpress.XtraBars.BarEditItem(); entityName = new DevExpress.XtraBars.BarEditItem(); keyword = new DevExpress.XtraBars.BarEditItem(); btnSearch = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem(); btnExport = new DevExpress.XtraBars.BarButtonItem();
            repositoryDateFrom = new DevExpress.XtraEditors.Repository.RepositoryItemDateEdit(); repositoryDateTo = new DevExpress.XtraEditors.Repository.RepositoryItemDateEdit(); repositoryUser = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit(); repositoryKeyword = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit(); repositoryAction = new DevExpress.XtraEditors.Repository.RepositoryItemComboBox(); repositoryEntity = new DevExpress.XtraEditors.Repository.RepositoryItemComboBox();
            barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); layoutResult = new DevExpress.XtraLayout.LayoutControlItem(); gridAudit = new DevExpress.XtraGrid.GridControl(); gridViewAudit = new DevExpress.XtraGrid.Views.Grid.GridView(); lblResult = new DevExpress.XtraEditors.LabelControl();
            colCreatedAt = new DevExpress.XtraGrid.Columns.GridColumn(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colUserName = new DevExpress.XtraGrid.Columns.GridColumn(); colAttemptedUser = new DevExpress.XtraGrid.Columns.GridColumn(); colAction = new DevExpress.XtraGrid.Columns.GridColumn(); colEntity = new DevExpress.XtraGrid.Columns.GridColumn(); colEntityId = new DevExpress.XtraGrid.Columns.GridColumn(); colDescription = new DevExpress.XtraGrid.Columns.GridColumn(); colMachine = new DevExpress.XtraGrid.Columns.GridColumn(); colIpAddress = new DevExpress.XtraGrid.Columns.GridColumn(); colCorrelationId = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateFrom).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateFrom.CalendarTimeProperties).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateTo).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateTo.CalendarTimeProperties).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryUser).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryKeyword).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryAction).BeginInit(); ((System.ComponentModel.ISupportInitialize)repositoryEntity).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutResult).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridAudit).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewAudit).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { dateFrom, dateTo, userKeyword, actionCode, entityName, keyword, btnSearch, btnReload, btnExport }); barManager.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] { repositoryDateFrom, repositoryDateTo, repositoryUser, repositoryKeyword, repositoryAction, repositoryEntity }); barManager.MainMenu = barTools;
            barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(dateFrom), new DevExpress.XtraBars.LinkPersistInfo(dateTo), new DevExpress.XtraBars.LinkPersistInfo(userKeyword), new DevExpress.XtraBars.LinkPersistInfo(actionCode), new DevExpress.XtraBars.LinkPersistInfo(entityName), new DevExpress.XtraBars.LinkPersistInfo(keyword), new DevExpress.XtraBars.LinkPersistInfo(btnSearch), new DevExpress.XtraBars.LinkPersistInfo(btnReload), new DevExpress.XtraBars.LinkPersistInfo(btnExport) }); ConfigureBarAppearance(barTools);
            ConfigureEdit(dateFrom, "開始日期", repositoryDateFrom, 110); ConfigureEdit(dateTo, "結束日期", repositoryDateTo, 110); ConfigureEdit(userKeyword, "使用者", repositoryUser, 120); ConfigureEdit(actionCode, "動作", repositoryAction, 170); ConfigureEdit(entityName, "對象", repositoryEntity, 150); ConfigureEdit(keyword, "關鍵字", repositoryKeyword, 150);
            repositoryDateFrom.Mask.EditMask = repositoryDateTo.Mask.EditMask = "yyyy/MM/dd"; repositoryDateFrom.Mask.UseMaskAsDisplayFormat = repositoryDateTo.Mask.UseMaskAsDisplayFormat = true; repositoryUser.NullValuePrompt = "帳號"; repositoryKeyword.NullValuePrompt = "說明或對象識別碼"; repositoryAction.TextEditStyle = repositoryEntity.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
            ConfigureButton(btnSearch, "查詢", Winform4System.Helpers.SvgIconCatalog.Search); btnSearch.ItemClick += btnSearch_ItemClick; ConfigureButton(btnReload, "清除並重新載入", Winform4System.Helpers.SvgIconCatalog.Refresh); btnReload.ItemClick += btnReload_ItemClick; ConfigureButton(btnExport, "匯出 Excel", Winform4System.Helpers.SvgIconCatalog.ExportExcel); btnExport.ItemClick += btnExport_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1400, 98); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridAudit); layoutControl.Controls.Add(lblResult); layoutControl.Root = Root;
            gridAudit.MainView = gridViewAudit; gridAudit.ViewCollection.Add(gridViewAudit); gridViewAudit.GridControl = gridAudit; ConfigureGrid(gridViewAudit); gridViewAudit.PopupMenuShowing += gridViewAudit_PopupMenuShowing; gridViewAudit.DoubleClick += gridViewAudit_DoubleClick;
            gridViewAudit.Columns.AddRange(new[] { colCreatedAt, colUserId, colUserName, colAttemptedUser, colAction, colEntity, colEntityId, colDescription, colMachine, colIpAddress, colCorrelationId }); ConfigureColumn(colCreatedAt, "CreatedAtLocal", "時間", 155, 0); colCreatedAt.DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime; colCreatedAt.DisplayFormat.FormatString = "yyyy/MM/dd HH:mm:ss"; ConfigureColumn(colUserId, "UserId", "操作帳號", 115, 1); ConfigureColumn(colUserName, "UserDisplayName", "操作人員", 130, 2); ConfigureColumn(colAttemptedUser, "AttemptedUserId", "嘗試登入帳號", 125, 3); ConfigureColumn(colAction, "ActionCode", "動作代碼", 190, 4); ConfigureColumn(colEntity, "EntityName", "對象類型", 165, 5); ConfigureColumn(colEntityId, "EntityId", "對象識別碼", 120, 6); ConfigureColumn(colDescription, "Description", "說明", 360, 7); ConfigureColumn(colMachine, "MachineName", "電腦名稱", 130, 8); ConfigureColumn(colIpAddress, "IpAddress", "IP 位址", 115, 9); ConfigureColumn(colCorrelationId, "CorrelationId", "關聯識別碼", 250, 10);
            lblResult.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); lblResult.Appearance.Options.UseFont = true; lblResult.Text = "共 0 筆記錄";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutResult, layoutGrid }); layoutResult.Control = lblResult; layoutResult.TextVisible = false; layoutResult.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom; layoutResult.MaxSize = new System.Drawing.Size(0, 32); layoutResult.MinSize = new System.Drawing.Size(1, 32); layoutGrid.Control = gridAudit; layoutGrid.TextVisible = false;
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "AuditLogView"; Size = new System.Drawing.Size(1400, 760); Load += AuditLogView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateFrom.CalendarTimeProperties).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateFrom).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateTo.CalendarTimeProperties).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryDateTo).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryUser).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryKeyword).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryAction).EndInit(); ((System.ComponentModel.ISupportInitialize)repositoryEntity).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutResult).EndInit(); ((System.ComponentModel.ISupportInitialize)gridAudit).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewAudit).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureEdit(DevExpress.XtraBars.BarEditItem item, string caption, DevExpress.XtraEditors.Repository.RepositoryItem repository, int width) { item.Caption = caption; item.Edit = repository; item.EditWidth = width; item.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; }
        private static void ConfigureButton(DevExpress.XtraBars.BarButtonItem item, string caption, DevExpress.Utils.Svg.SvgImage icon) { item.Caption = caption; item.ImageOptions.SvgImage = icon; item.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); item.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; }
        private static void ConfigureBarAppearance(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void ConfigureGrid(DevExpress.XtraGrid.Views.Grid.GridView view) { view.OptionsBehavior.Editable = false; view.OptionsSelection.EnableAppearanceFocusedCell = false; view.OptionsSelection.EnableAppearanceHotTrackedRow = DevExpress.Utils.DefaultBoolean.True; view.OptionsView.ColumnAutoWidth = false; view.OptionsView.EnableAppearanceOddRow = true; view.OptionsView.ShowAutoFilterRow = true; view.OptionsView.ShowGroupPanel = false; view.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); view.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; view.Appearance.HeaderPanel.Options.UseFont = true; view.Appearance.HeaderPanel.Options.UseForeColor = true; view.Appearance.HeaderPanel.Options.UseTextOptions = true; view.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; view.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); view.Appearance.Row.ForeColor = System.Drawing.Color.Black; view.Appearance.Row.Options.UseFont = true; view.Appearance.Row.Options.UseForeColor = true; }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
    }
}
