namespace Winform4System.Forms.SystemManagement
{
    partial class AuditLogDetailForm
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnClose; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlGroup groupIdentity, groupContent;
        private DevExpress.XtraLayout.LayoutControlItem layoutCreatedAt, layoutUser, layoutAttemptedUser, layoutAction, layoutEntity, layoutEntityId, layoutMachine, layoutIpAddress, layoutCorrelationId, layoutDescription, layoutData;
        private DevExpress.XtraEditors.TextEdit txbCreatedAt, txbUser, txbAttemptedUser, txbAction, txbEntity, txbEntityId, txbMachine, txbIpAddress, txbCorrelationId; private DevExpress.XtraEditors.MemoEdit memoDescription, memoData;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnClose = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); groupIdentity = new DevExpress.XtraLayout.LayoutControlGroup(); groupContent = new DevExpress.XtraLayout.LayoutControlGroup(); layoutCreatedAt = new DevExpress.XtraLayout.LayoutControlItem(); layoutUser = new DevExpress.XtraLayout.LayoutControlItem(); layoutAttemptedUser = new DevExpress.XtraLayout.LayoutControlItem(); layoutAction = new DevExpress.XtraLayout.LayoutControlItem(); layoutEntity = new DevExpress.XtraLayout.LayoutControlItem(); layoutEntityId = new DevExpress.XtraLayout.LayoutControlItem(); layoutMachine = new DevExpress.XtraLayout.LayoutControlItem(); layoutIpAddress = new DevExpress.XtraLayout.LayoutControlItem(); layoutCorrelationId = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); layoutData = new DevExpress.XtraLayout.LayoutControlItem(); txbCreatedAt = new DevExpress.XtraEditors.TextEdit(); txbUser = new DevExpress.XtraEditors.TextEdit(); txbAttemptedUser = new DevExpress.XtraEditors.TextEdit(); txbAction = new DevExpress.XtraEditors.TextEdit(); txbEntity = new DevExpress.XtraEditors.TextEdit(); txbEntityId = new DevExpress.XtraEditors.TextEdit(); txbMachine = new DevExpress.XtraEditors.TextEdit(); txbIpAddress = new DevExpress.XtraEditors.TextEdit(); txbCorrelationId = new DevExpress.XtraEditors.TextEdit(); memoDescription = new DevExpress.XtraEditors.MemoEdit(); memoData = new DevExpress.XtraEditors.MemoEdit();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)groupIdentity).BeginInit(); ((System.ComponentModel.ISupportInitialize)groupContent).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutCreatedAt).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutUser).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutAttemptedUser).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutAction).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutEntity).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutEntityId).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutMachine).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutIpAddress).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutCorrelationId).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutDescription).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutData).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbCreatedAt.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbUser.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbAttemptedUser.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbAction.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbEntity.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbEntityId.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbMachine.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbIpAddress.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbCorrelationId.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoData.Properties).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.Add(btnClose); barManager.MainMenu = barTools; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.Add(new DevExpress.XtraBars.LinkPersistInfo(btnClose)); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; ConfigureBarAppearance(barTools); btnClose.Caption = "關閉"; btnClose.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Close; btnClose.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnClose.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnClose.ItemClick += btnClose_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(980, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Root = Root; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbCreatedAt, txbUser, txbAttemptedUser, txbAction, txbEntity, txbEntityId, txbMachine, txbIpAddress, txbCorrelationId, memoDescription, memoData });
            ConfigureReadOnly(txbCreatedAt); ConfigureReadOnly(txbUser); ConfigureReadOnly(txbAttemptedUser); ConfigureReadOnly(txbAction); ConfigureReadOnly(txbEntity); ConfigureReadOnly(txbEntityId); ConfigureReadOnly(txbMachine); ConfigureReadOnly(txbIpAddress); ConfigureReadOnly(txbCorrelationId); ConfigureReadOnly(memoDescription); ConfigureReadOnly(memoData);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { groupIdentity, groupContent }); groupIdentity.Text = "記錄資訊"; groupIdentity.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCreatedAt, layoutUser, layoutAttemptedUser, layoutAction, layoutEntity, layoutEntityId, layoutMachine, layoutIpAddress, layoutCorrelationId }); groupContent.Text = "詳細內容"; groupContent.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutDescription, layoutData });
            ConfigureItem(layoutCreatedAt, txbCreatedAt, "時間"); ConfigureItem(layoutUser, txbUser, "操作人員"); ConfigureItem(layoutAttemptedUser, txbAttemptedUser, "嘗試登入帳號"); ConfigureItem(layoutAction, txbAction, "動作代碼"); ConfigureItem(layoutEntity, txbEntity, "對象類型"); ConfigureItem(layoutEntityId, txbEntityId, "對象識別碼"); ConfigureItem(layoutMachine, txbMachine, "電腦名稱"); ConfigureItem(layoutIpAddress, txbIpAddress, "IP 位址"); ConfigureItem(layoutCorrelationId, txbCorrelationId, "關聯識別碼"); ConfigureItem(layoutDescription, memoDescription, "說明"); ConfigureItem(layoutData, memoData, "資料內容"); layoutDescription.MinSize = new System.Drawing.Size(1, 100); layoutData.MinSize = new System.Drawing.Size(1, 180);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(980, 720); MinimumSize = new System.Drawing.Size(820, 620); StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "稽核記錄詳細資料";
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)groupIdentity).EndInit(); ((System.ComponentModel.ISupportInitialize)groupContent).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutCreatedAt).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutUser).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutAttemptedUser).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutAction).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutEntity).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutEntityId).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutMachine).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutIpAddress).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutCorrelationId).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutDescription).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutData).EndInit(); ((System.ComponentModel.ISupportInitialize)txbCreatedAt.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbUser.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbAttemptedUser.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbAction.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbEntity.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbEntityId.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbMachine.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbIpAddress.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbCorrelationId.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoData.Properties).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureReadOnly(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.ReadOnly = true; editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.ForeColor = System.Drawing.Color.Black; editor.Properties.Appearance.Options.UseFont = true; editor.Properties.Appearance.Options.UseForeColor = true; }
        private static void ConfigureItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string caption) { item.Control = control; item.Text = caption; item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.ForeColor = System.Drawing.Color.Black; item.AppearanceItemCaption.Options.UseFont = true; item.AppearanceItemCaption.Options.UseForeColor = true; item.TextSize = new System.Drawing.Size(120, 25); }
        private static void ConfigureBarAppearance(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
    }
}
