namespace Winform4System.Forms.SystemManagement
{
    partial class DepartmentManagementView
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarButtonItem btnAdd, btnReload;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutTree;
        private DevExpress.XtraTreeList.TreeList treeDepartments;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colDepartmentName, colDepartmentCode, colSortOrder, colEmployeeCount, colChildCount, colStatus;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnAdd = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutTree = new DevExpress.XtraLayout.LayoutControlItem(); treeDepartments = new DevExpress.XtraTreeList.TreeList(); colDepartmentName = new DevExpress.XtraTreeList.Columns.TreeListColumn(); colDepartmentCode = new DevExpress.XtraTreeList.Columns.TreeListColumn(); colSortOrder = new DevExpress.XtraTreeList.Columns.TreeListColumn(); colEmployeeCount = new DevExpress.XtraTreeList.Columns.TreeListColumn(); colChildCount = new DevExpress.XtraTreeList.Columns.TreeListColumn(); colStatus = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutTree).BeginInit(); ((System.ComponentModel.ISupportInitialize)treeDepartments).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnAdd, btnReload }); barManager.MainMenu = barTools; barManager.MaxItemId = 2;
            barTools.BarName = "部門管理工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnAdd), new DevExpress.XtraBars.LinkPersistInfo(btnReload) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; ConfigureBarFont(barTools);
            btnAdd.Caption = "新增部門"; btnAdd.Id = 0; btnAdd.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Add; btnAdd.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnAdd.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnAdd.ItemClick += btnAdd_ItemClick;
            btnReload.Caption = "重新載入"; btnReload.Id = 1; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(treeDepartments); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(1200, 671);
            treeDepartments.Location = new System.Drawing.Point(12, 12); treeDepartments.Size = new System.Drawing.Size(1176, 647); treeDepartments.KeyFieldName = "DepartmentId"; treeDepartments.ParentFieldName = "ParentDepartmentId"; treeDepartments.OptionsBehavior.Editable = false; treeDepartments.OptionsSelection.EnableAppearanceFocusedCell = false; treeDepartments.OptionsView.ShowAutoFilterRow = true; treeDepartments.OptionsView.ShowHorzLines = true; treeDepartments.OptionsView.ShowVertLines = false; treeDepartments.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); treeDepartments.Appearance.HeaderPanel.Options.UseFont = true; treeDepartments.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; treeDepartments.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); treeDepartments.Appearance.Row.Options.UseFont = true; treeDepartments.PopupMenuShowing += treeDepartments_PopupMenuShowing;
            treeDepartments.Columns.AddRange(new[] { colDepartmentName, colDepartmentCode, colSortOrder, colEmployeeCount, colChildCount, colStatus }); ConfigureColumn(colDepartmentName, "DepartmentName", "部門名稱", 280, 0); ConfigureColumn(colDepartmentCode, "DepartmentCode", "部門代碼", 150, 1); ConfigureColumn(colSortOrder, "SortOrder", "排序", 80, 2); ConfigureColumn(colEmployeeCount, "EmployeeCount", "有效人員數", 110, 3); ConfigureColumn(colChildCount, "ChildCount", "下層部門數", 110, 4); ConfigureColumn(colStatus, "StatusDisplay", "狀態", 90, 5);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutTree }); Root.Size = new System.Drawing.Size(1200, 671); layoutTree.Control = treeDepartments; layoutTree.TextVisible = false; layoutTree.Size = new System.Drawing.Size(1180, 651);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "DepartmentManagementView"; Size = new System.Drawing.Size(1200, 720); Load += DepartmentManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutTree).EndInit(); ((System.ComponentModel.ISupportInitialize)treeDepartments).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureColumn(DevExpress.XtraTreeList.Columns.TreeListColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = font; bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
