namespace Winform4System.Forms.SystemManagement
{
    partial class EmployeeEditForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraEditors.TextEdit txbUserId, txbDisplayNameTW, txbDisplayNameVN, txbEmail, txbPhone;
        private DevExpress.XtraEditors.LookUpEdit cbbDepartment, cbbJobTitle; private DevExpress.XtraEditors.ComboBoxEdit cbbEmploymentStatus; private DevExpress.XtraEditors.DateEdit dateHire; private DevExpress.XtraEditors.CheckEdit chkAccountActive;
        private DevExpress.XtraLayout.LayoutControlItem layoutUserId, layoutDisplayNameTW, layoutDisplayNameVN, layoutDepartment, layoutJobTitle, layoutEmail, layoutPhone, layoutHireDate, layoutEmploymentStatus, layoutAccountActive;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); txbUserId = new DevExpress.XtraEditors.TextEdit(); txbDisplayNameTW = new DevExpress.XtraEditors.TextEdit(); txbDisplayNameVN = new DevExpress.XtraEditors.TextEdit(); txbEmail = new DevExpress.XtraEditors.TextEdit(); txbPhone = new DevExpress.XtraEditors.TextEdit(); cbbDepartment = new DevExpress.XtraEditors.LookUpEdit(); cbbJobTitle = new DevExpress.XtraEditors.LookUpEdit(); cbbEmploymentStatus = new DevExpress.XtraEditors.ComboBoxEdit(); dateHire = new DevExpress.XtraEditors.DateEdit(); chkAccountActive = new DevExpress.XtraEditors.CheckEdit(); layoutUserId = new DevExpress.XtraLayout.LayoutControlItem(); layoutDisplayNameTW = new DevExpress.XtraLayout.LayoutControlItem(); layoutDisplayNameVN = new DevExpress.XtraLayout.LayoutControlItem(); layoutDepartment = new DevExpress.XtraLayout.LayoutControlItem(); layoutJobTitle = new DevExpress.XtraLayout.LayoutControlItem(); layoutEmail = new DevExpress.XtraLayout.LayoutControlItem(); layoutPhone = new DevExpress.XtraLayout.LayoutControlItem(); layoutHireDate = new DevExpress.XtraLayout.LayoutControlItem(); layoutEmploymentStatus = new DevExpress.XtraLayout.LayoutControlItem(); layoutAccountActive = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barTools;
            barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; barTools.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); barTools.BarAppearance.Disabled.Options.UseFont = true; barTools.BarAppearance.Hovered.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Hovered.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Hovered.Options.UseFont = true; barTools.BarAppearance.Hovered.Options.UseForeColor = true; barTools.BarAppearance.Normal.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Normal.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Normal.Options.UseFont = true; barTools.BarAppearance.Normal.Options.UseForeColor = true; barTools.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Pressed.Options.UseFont = true; barTools.BarAppearance.Pressed.Options.UseForeColor = true;
            btnSave.Caption = "儲存"; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick; btnCancel.Caption = "取消"; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(700, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Root = Root; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Size = new System.Drawing.Size(700, 451); layoutControl.AllowCustomization = false;
            layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbUserId, txbDisplayNameTW, txbDisplayNameVN, cbbDepartment, cbbJobTitle, txbEmail, txbPhone, dateHire, cbbEmploymentStatus, chkAccountActive });
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutUserId, layoutDisplayNameTW, layoutDisplayNameVN, layoutDepartment, layoutJobTitle, layoutEmail, layoutPhone, layoutHireDate, layoutEmploymentStatus, layoutAccountActive });
            ConfigureItem(layoutUserId, txbUserId, "人員編號"); ConfigureItem(layoutDisplayNameTW, txbDisplayNameTW, "中文姓名"); ConfigureItem(layoutDisplayNameVN, txbDisplayNameVN, "越文姓名"); ConfigureItem(layoutDepartment, cbbDepartment, "部門"); ConfigureItem(layoutJobTitle, cbbJobTitle, "職稱"); ConfigureItem(layoutEmail, txbEmail, "公司電子郵件"); ConfigureItem(layoutPhone, txbPhone, "公司電話"); ConfigureItem(layoutHireDate, dateHire, "到職日期"); ConfigureItem(layoutEmploymentStatus, cbbEmploymentStatus, "任職狀態"); ConfigureItem(layoutAccountActive, chkAccountActive, "");
            ConfigureEditor(txbUserId); ConfigureEditor(txbDisplayNameTW); ConfigureEditor(txbDisplayNameVN); ConfigureEditor(cbbDepartment); ConfigureEditor(cbbJobTitle); ConfigureEditor(txbEmail); ConfigureEditor(txbPhone); ConfigureEditor(dateHire); ConfigureEditor(cbbEmploymentStatus); ConfigureEditor(chkAccountActive); cbbEmploymentStatus.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); cbbEmploymentStatus.Properties.AppearanceDropDown.Options.UseFont = true; cbbDepartment.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); cbbDepartment.Properties.AppearanceDropDown.Options.UseFont = true; cbbJobTitle.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); cbbJobTitle.Properties.AppearanceDropDown.Options.UseFont = true;
            chkAccountActive.Text = "啟用登入帳號"; cbbEmploymentStatus.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Size = new System.Drawing.Size(700, 451);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(700, 500); Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow; MaximizeBox = false; MinimizeBox = false; StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "人員資料"; IconOptions.Icon = Winform4System.Properties.Resources.AppIcon;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string caption) { item.Control = control; item.Text = caption; item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.ForeColor = System.Drawing.Color.Black; item.AppearanceItemCaption.Options.UseFont = true; item.AppearanceItemCaption.Options.UseForeColor = true; item.TextSize = new System.Drawing.Size(120, 24); if (string.IsNullOrEmpty(caption)) item.TextVisible = false; }
        private static void ConfigureEditor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.ForeColor = System.Drawing.Color.Black; editor.Properties.Appearance.Options.UseFont = true; editor.Properties.Appearance.Options.UseForeColor = true; }
    }
}
