namespace Winform4System.Forms.SystemManagement
{
    partial class EmployeeManagementView
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarButtonItem btnAdd;
        private DevExpress.XtraBars.BarButtonItem btnReload;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutGrid;
        private DevExpress.XtraGrid.GridControl gridEmployees;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewEmployees;
        private DevExpress.XtraGrid.Columns.GridColumn colUserId, colDisplayNameTW, colDisplayNameVN, colDepartmentName, colEmploymentStatus, colWorkEmail, colWorkPhone, colAuthenticationType, colIsAccountActive;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnAdd = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem();
            barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem();
            gridEmployees = new DevExpress.XtraGrid.GridControl(); gridViewEmployees = new DevExpress.XtraGrid.Views.Grid.GridView(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameTW = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameVN = new DevExpress.XtraGrid.Columns.GridColumn(); colDepartmentName = new DevExpress.XtraGrid.Columns.GridColumn(); colEmploymentStatus = new DevExpress.XtraGrid.Columns.GridColumn(); colWorkEmail = new DevExpress.XtraGrid.Columns.GridColumn(); colWorkPhone = new DevExpress.XtraGrid.Columns.GridColumn(); colAuthenticationType = new DevExpress.XtraGrid.Columns.GridColumn(); colIsAccountActive = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridEmployees).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewEmployees).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnAdd, btnReload }); barManager.MainMenu = barTools; barManager.MaxItemId = 2;
            barTools.BarName = "人員工具列"; barTools.DockCol = 0; barTools.DockRow = 0; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnAdd), new DevExpress.XtraBars.LinkPersistInfo(btnReload) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true;
            barTools.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); barTools.BarAppearance.Disabled.Options.UseFont = true; barTools.BarAppearance.Hovered.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Hovered.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Hovered.Options.UseFont = true; barTools.BarAppearance.Hovered.Options.UseForeColor = true; barTools.BarAppearance.Normal.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Normal.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Normal.Options.UseFont = true; barTools.BarAppearance.Normal.Options.UseForeColor = true; barTools.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); barTools.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; barTools.BarAppearance.Pressed.Options.UseFont = true; barTools.BarAppearance.Pressed.Options.UseForeColor = true;
            btnAdd.Caption = "新增人員"; btnAdd.Id = 0; btnAdd.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Add; btnAdd.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnAdd.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnAdd.ItemClick += btnAdd_ItemClick;
            btnReload.Caption = "重新載入"; btnReload.Id = 1; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Controls.Add(gridEmployees); layoutControl.Root = Root; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Size = new System.Drawing.Size(1200, 671); layoutControl.AllowCustomization = false;
            gridEmployees.Location = new System.Drawing.Point(12, 12); gridEmployees.MainView = gridViewEmployees; gridEmployees.Size = new System.Drawing.Size(1176, 647); gridEmployees.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gridViewEmployees });
            gridViewEmployees.GridControl = gridEmployees; gridViewEmployees.OptionsBehavior.Editable = false; gridViewEmployees.OptionsSelection.EnableAppearanceFocusedCell = false; gridViewEmployees.OptionsSelection.EnableAppearanceHotTrackedRow = DevExpress.Utils.DefaultBoolean.True; gridViewEmployees.OptionsView.ColumnAutoWidth = false; gridViewEmployees.OptionsView.EnableAppearanceOddRow = true; gridViewEmployees.OptionsView.ShowAutoFilterRow = true; gridViewEmployees.OptionsView.ShowGroupPanel = false; gridViewEmployees.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); gridViewEmployees.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; gridViewEmployees.Appearance.HeaderPanel.Options.UseFont = true; gridViewEmployees.Appearance.HeaderPanel.Options.UseForeColor = true; gridViewEmployees.Appearance.HeaderPanel.Options.UseTextOptions = true; gridViewEmployees.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; gridViewEmployees.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); gridViewEmployees.Appearance.Row.ForeColor = System.Drawing.Color.Black; gridViewEmployees.Appearance.Row.Options.UseFont = true; gridViewEmployees.Appearance.Row.Options.UseForeColor = true; gridViewEmployees.PopupMenuShowing += gridViewEmployees_PopupMenuShowing;
            gridViewEmployees.Columns.AddRange(new[] { colUserId, colDisplayNameTW, colDisplayNameVN, colDepartmentName, colEmploymentStatus, colWorkEmail, colWorkPhone, colAuthenticationType, colIsAccountActive });
            ConfigureColumn(colUserId, "UserId", "人員編號", 100, 0); ConfigureColumn(colDisplayNameTW, "DisplayNameTW", "中文姓名", 130, 1); ConfigureColumn(colDisplayNameVN, "DisplayNameVN", "越文姓名", 180, 2); ConfigureColumn(colDepartmentName, "DepartmentName", "部門", 150, 3); ConfigureColumn(colEmploymentStatus, "EmploymentStatusDisplay", "任職狀態", 100, 4); ConfigureColumn(colWorkEmail, "WorkEmail", "公司電子郵件", 190, 5); ConfigureColumn(colWorkPhone, "WorkPhone", "公司電話", 110, 6); ConfigureColumn(colAuthenticationType, "AuthenticationTypeDisplay", "驗證方式", 100, 7); ConfigureColumn(colIsAccountActive, "IsAccountActive", "帳號啟用", 80, 8);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); Root.Size = new System.Drawing.Size(1200, 671); layoutGrid.Control = gridEmployees; layoutGrid.TextVisible = false; layoutGrid.Size = new System.Drawing.Size(1180, 651);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "EmployeeManagementView"; Size = new System.Drawing.Size(1200, 720); Load += EmployeeManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridEmployees).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewEmployees).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
    }
}
