namespace Winform4System.Forms.SystemManagement
{
    partial class EmployeeDepartmentTransferForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barCommands;
        private DevExpress.XtraBars.BarButtonItem btnConfirm, btnCancel;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraEditors.LabelControl lblInformation;
        private DevExpress.XtraEditors.LookUpEdit cbbTargetDepartment;
        private DevExpress.XtraGrid.GridControl gridEmployees;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewEmployees;
        private DevExpress.XtraGrid.Columns.GridColumn colUserId, colDisplayNameTW, colDisplayNameVN, colEmploymentStatus;
        private DevExpress.XtraLayout.LayoutControlItem layoutInformation, layoutTargetDepartment, layoutEmployees;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            barManager = new DevExpress.XtraBars.BarManager(components); barCommands = new DevExpress.XtraBars.Bar(); btnConfirm = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); lblInformation = new DevExpress.XtraEditors.LabelControl(); cbbTargetDepartment = new DevExpress.XtraEditors.LookUpEdit(); gridEmployees = new DevExpress.XtraGrid.GridControl(); gridViewEmployees = new DevExpress.XtraGrid.Views.Grid.GridView(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameTW = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameVN = new DevExpress.XtraGrid.Columns.GridColumn(); colEmploymentStatus = new DevExpress.XtraGrid.Columns.GridColumn(); layoutInformation = new DevExpress.XtraLayout.LayoutControlItem(); layoutTargetDepartment = new DevExpress.XtraLayout.LayoutControlItem(); layoutEmployees = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)cbbTargetDepartment.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridEmployees).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewEmployees).BeginInit(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutInformation).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutTargetDepartment).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutEmployees).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barCommands }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnConfirm, btnCancel }); barManager.MainMenu = barCommands; barManager.MaxItemId = 2;
            barCommands.BarName = "人員轉移工具列"; barCommands.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barCommands.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnConfirm), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barCommands.OptionsBar.AllowQuickCustomization = false; barCommands.OptionsBar.DrawDragBorder = false; barCommands.OptionsBar.UseWholeRow = true; ConfigureBarFont(barCommands);
            btnConfirm.Caption = "確認轉移"; btnConfirm.Id = 0; btnConfirm.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.UserTransfer; btnConfirm.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnConfirm.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnConfirm.ItemClick += btnConfirm_ItemClick;
            btnCancel.Caption = "取消"; btnCancel.Id = 1; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(900, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { lblInformation, cbbTargetDepartment, gridEmployees }); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(900, 551);
            lblInformation.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); lblInformation.Appearance.ForeColor = System.Drawing.Color.Black; lblInformation.Appearance.Options.UseFont = true; lblInformation.Appearance.Options.UseForeColor = true; lblInformation.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap; lblInformation.AutoSizeMode = DevExpress.XtraEditors.LabelAutoSizeMode.Vertical; lblInformation.StyleController = layoutControl;
            cbbTargetDepartment.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); cbbTargetDepartment.Properties.Appearance.Options.UseFont = true; cbbTargetDepartment.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); cbbTargetDepartment.Properties.AppearanceDropDown.Options.UseFont = true; cbbTargetDepartment.Properties.Buttons.AddRange(new[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) }); cbbTargetDepartment.Properties.Columns.AddRange(new[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("DisplayName", "目標部門") }); cbbTargetDepartment.Properties.NullText = "請選擇目標部門"; cbbTargetDepartment.StyleController = layoutControl;
            gridEmployees.MainView = gridViewEmployees; gridEmployees.ViewCollection.Add(gridViewEmployees); gridViewEmployees.GridControl = gridEmployees; gridViewEmployees.OptionsBehavior.Editable = false; gridViewEmployees.OptionsSelection.EnableAppearanceFocusedCell = false; gridViewEmployees.OptionsView.ColumnAutoWidth = false; gridViewEmployees.OptionsView.ShowAutoFilterRow = true; gridViewEmployees.OptionsView.ShowGroupPanel = false; gridViewEmployees.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); gridViewEmployees.Appearance.HeaderPanel.Options.UseFont = true; gridViewEmployees.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; gridViewEmployees.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); gridViewEmployees.Appearance.Row.Options.UseFont = true;
            gridViewEmployees.Columns.AddRange(new[] { colUserId, colDisplayNameTW, colDisplayNameVN, colEmploymentStatus }); ConfigureColumn(colUserId, "UserId", "人員編號", 130, 0); ConfigureColumn(colDisplayNameTW, "DisplayNameTW", "中文姓名", 180, 1); ConfigureColumn(colDisplayNameVN, "DisplayNameVN", "越文姓名", 260, 2); ConfigureColumn(colEmploymentStatus, "EmploymentStatusDisplay", "任職狀態", 120, 3);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutInformation, layoutTargetDepartment, layoutEmployees }); Root.Size = new System.Drawing.Size(900, 551);
            layoutInformation.Control = lblInformation; layoutInformation.Location = new System.Drawing.Point(0, 0); layoutInformation.Size = new System.Drawing.Size(880, 62); layoutInformation.TextVisible = false;
            layoutTargetDepartment.Control = cbbTargetDepartment; layoutTargetDepartment.Location = new System.Drawing.Point(0, 62); layoutTargetDepartment.Size = new System.Drawing.Size(880, 40); layoutTargetDepartment.Text = "目標部門"; layoutTargetDepartment.TextSize = new System.Drawing.Size(90, 24); layoutTargetDepartment.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); layoutTargetDepartment.AppearanceItemCaption.Options.UseFont = true;
            layoutEmployees.Control = gridEmployees; layoutEmployees.Location = new System.Drawing.Point(0, 102); layoutEmployees.Size = new System.Drawing.Size(880, 429); layoutEmployees.TextVisible = false;
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(900, 600); Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog; IconOptions.Icon = global::Winform4System.Properties.Resources.AppIcon; MaximizeBox = false; MinimizeBox = false; Name = "EmployeeDepartmentTransferForm"; StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "轉移部門人員";
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)cbbTargetDepartment.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)gridEmployees).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewEmployees).EndInit(); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutInformation).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutTargetDepartment).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutEmployees).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = font; bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
