namespace Winform4System.Forms.SystemManagement
{
    partial class JobTitleEditForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barCommands; private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraEditors.TextEdit txbCode, txbName; private DevExpress.XtraEditors.SpinEdit spinSortOrder; private DevExpress.XtraEditors.CheckEdit chkActive; private DevExpress.XtraLayout.LayoutControlItem layoutCode, layoutName, layoutSortOrder, layoutActive; private DevExpress.XtraLayout.EmptySpaceItem emptySpace;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barCommands = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); txbCode = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); spinSortOrder = new DevExpress.XtraEditors.SpinEdit(); chkActive = new DevExpress.XtraEditors.CheckEdit(); layoutCode = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutSortOrder = new DevExpress.XtraLayout.LayoutControlItem(); layoutActive = new DevExpress.XtraLayout.LayoutControlItem(); emptySpace = new DevExpress.XtraLayout.EmptySpaceItem();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)spinSortOrder.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)chkActive.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutCode).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutName).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutSortOrder).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutActive).BeginInit(); ((System.ComponentModel.ISupportInitialize)emptySpace).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barCommands }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barCommands; barManager.MaxItemId = 2;
            barCommands.BarName = "職稱編輯工具列"; barCommands.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barCommands.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barCommands.OptionsBar.AllowQuickCustomization = false; barCommands.OptionsBar.DrawDragBorder = false; barCommands.OptionsBar.UseWholeRow = true; ConfigureBarFont(barCommands);
            btnSave.Caption = "儲存"; btnSave.Id = 0; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick; btnCancel.Caption = "取消"; btnCancel.Id = 1; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(620, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbCode, txbName, spinSortOrder, chkActive }); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(620, 231);
            ConfigureEditor(txbCode); txbCode.StyleController = layoutControl; txbCode.Properties.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper; txbCode.Properties.MaxLength = 30; ConfigureEditor(txbName); txbName.StyleController = layoutControl; txbName.Properties.MaxLength = 200; ConfigureEditor(spinSortOrder); spinSortOrder.StyleController = layoutControl; spinSortOrder.Properties.Buttons.AddRange(new[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) }); spinSortOrder.Properties.IsFloatValue = false; spinSortOrder.Properties.MaskSettings.Set("mask", "d"); spinSortOrder.Properties.MaxValue = 999999; ConfigureEditor(chkActive); chkActive.StyleController = layoutControl; chkActive.Text = "啟用職稱";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSortOrder, layoutActive, emptySpace }); Root.Size = new System.Drawing.Size(620, 231); ConfigureItem(layoutCode, txbCode, "職稱代碼", 0); ConfigureItem(layoutName, txbName, "職稱名稱", 36); ConfigureItem(layoutSortOrder, spinSortOrder, "排序", 72); layoutActive.Control = chkActive; layoutActive.Location = new System.Drawing.Point(0, 108); layoutActive.Size = new System.Drawing.Size(600, 36); layoutActive.TextVisible = false; emptySpace.AllowHotTrack = false; emptySpace.Location = new System.Drawing.Point(0, 144); emptySpace.Size = new System.Drawing.Size(600, 67);
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(620, 280); Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog; IconOptions.Icon = global::Winform4System.Properties.Resources.AppIcon; MaximizeBox = false; MinimizeBox = false; Name = "JobTitleEditForm"; StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "職稱";
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)spinSortOrder.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)chkActive.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutCode).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutName).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutSortOrder).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutActive).EndInit(); ((System.ComponentModel.ISupportInitialize)emptySpace).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureEditor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.Options.UseFont = true; editor.Size = new System.Drawing.Size(488, 32); }
        private static void ConfigureItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string text, int top) { item.Control = control; item.Location = new System.Drawing.Point(0, top); item.Size = new System.Drawing.Size(600, 36); item.Text = text; item.TextSize = new System.Drawing.Size(100, 24); item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.Options.UseFont = true; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = font; bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
