namespace Winform4System.Forms.SystemManagement
{
    partial class JobTitleManagementView
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnAdd, btnReload; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutGrid; private DevExpress.XtraGrid.GridControl gridJobTitles; private DevExpress.XtraGrid.Views.Grid.GridView gridViewJobTitles; private DevExpress.XtraGrid.Columns.GridColumn colCode, colName, colSortOrder, colEmployeeCount, colStatus;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnAdd = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); gridJobTitles = new DevExpress.XtraGrid.GridControl(); gridViewJobTitles = new DevExpress.XtraGrid.Views.Grid.GridView(); colCode = new DevExpress.XtraGrid.Columns.GridColumn(); colName = new DevExpress.XtraGrid.Columns.GridColumn(); colSortOrder = new DevExpress.XtraGrid.Columns.GridColumn(); colEmployeeCount = new DevExpress.XtraGrid.Columns.GridColumn(); colStatus = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridJobTitles).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewJobTitles).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnAdd, btnReload }); barManager.MainMenu = barTools; barManager.MaxItemId = 2; barTools.BarName = "職稱管理工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnAdd), new DevExpress.XtraBars.LinkPersistInfo(btnReload) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; ConfigureBarFont(barTools);
            btnAdd.Caption = "新增職稱"; btnAdd.Id = 0; btnAdd.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Add; btnAdd.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnAdd.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnAdd.ItemClick += btnAdd_ItemClick; btnReload.Caption = "重新載入"; btnReload.Id = 1; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridJobTitles); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(1200, 671); gridJobTitles.Location = new System.Drawing.Point(12, 12); gridJobTitles.MainView = gridViewJobTitles; gridJobTitles.Size = new System.Drawing.Size(1176, 647); gridJobTitles.ViewCollection.Add(gridViewJobTitles); gridViewJobTitles.GridControl = gridJobTitles; gridViewJobTitles.OptionsBehavior.Editable = false; gridViewJobTitles.OptionsSelection.EnableAppearanceFocusedCell = false; gridViewJobTitles.OptionsView.ShowAutoFilterRow = true; gridViewJobTitles.OptionsView.ShowGroupPanel = false; gridViewJobTitles.OptionsView.ColumnAutoWidth = false; gridViewJobTitles.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); gridViewJobTitles.Appearance.HeaderPanel.Options.UseFont = true; gridViewJobTitles.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; gridViewJobTitles.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); gridViewJobTitles.Appearance.Row.Options.UseFont = true; gridViewJobTitles.PopupMenuShowing += gridViewJobTitles_PopupMenuShowing;
            gridViewJobTitles.Columns.AddRange(new[] { colCode, colName, colSortOrder, colEmployeeCount, colStatus }); ConfigureColumn(colCode, "JobTitleCode", "職稱代碼", 160, 0); ConfigureColumn(colName, "JobTitleName", "職稱名稱", 300, 1); ConfigureColumn(colSortOrder, "SortOrder", "排序", 90, 2); ConfigureColumn(colEmployeeCount, "EmployeeCount", "有效人員數", 120, 3); ConfigureColumn(colStatus, "StatusDisplay", "狀態", 100, 4);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); Root.Size = new System.Drawing.Size(1200, 671); layoutGrid.Control = gridJobTitles; layoutGrid.TextVisible = false; layoutGrid.Size = new System.Drawing.Size(1180, 651); Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "JobTitleManagementView"; Size = new System.Drawing.Size(1200, 720); Load += JobTitleManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridJobTitles).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewJobTitles).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = font; bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
