namespace Winform4System.Forms.SystemManagement
{
    partial class RolePermissionManagementView
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnAdd, btnReload; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutGrid; private DevExpress.XtraGrid.GridControl gridRoles; private DevExpress.XtraGrid.Views.Grid.GridView gridViewRoles; private DevExpress.XtraGrid.Columns.GridColumn colId, colCode, colName, colDescription, colPermissionCount, colGroupCount, colSystem, colActive;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnAdd = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); gridRoles = new DevExpress.XtraGrid.GridControl(); gridViewRoles = new DevExpress.XtraGrid.Views.Grid.GridView(); colId = new DevExpress.XtraGrid.Columns.GridColumn(); colCode = new DevExpress.XtraGrid.Columns.GridColumn(); colName = new DevExpress.XtraGrid.Columns.GridColumn(); colDescription = new DevExpress.XtraGrid.Columns.GridColumn(); colPermissionCount = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupCount = new DevExpress.XtraGrid.Columns.GridColumn(); colSystem = new DevExpress.XtraGrid.Columns.GridColumn(); colActive = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridRoles).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewRoles).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnAdd, btnReload }); barManager.MainMenu = barTools; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnAdd), new DevExpress.XtraBars.LinkPersistInfo(btnReload) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true; ConfigureBar(barTools);
            btnAdd.Caption = "新增角色"; btnAdd.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Add; btnAdd.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnAdd.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnAdd.ItemClick += btnAdd_ItemClick; btnReload.Caption = "重新載入"; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridRoles); layoutControl.Root = Root; gridRoles.MainView = gridViewRoles; gridRoles.ViewCollection.Add(gridViewRoles); gridViewRoles.GridControl = gridRoles; ConfigureGrid(gridViewRoles); gridViewRoles.PopupMenuShowing += gridViewRoles_PopupMenuShowing; gridViewRoles.Columns.AddRange(new[] { colId, colCode, colName, colDescription, colPermissionCount, colGroupCount, colSystem, colActive }); Column(colId, "RoleId", "識別碼", 70, 0); Column(colCode, "RoleCode", "角色代碼", 170, 1); Column(colName, "RoleName", "角色名稱", 180, 2); Column(colDescription, "Description", "角色說明", 280, 3); Column(colPermissionCount, "PermissionCount", "權限數", 85, 4); Column(colGroupCount, "GroupCount", "群組數", 85, 5); Column(colSystem, "IsSystemRole", "系統角色", 90, 6); Column(colActive, "IsActive", "啟用", 70, 7);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); layoutGrid.Control = gridRoles; layoutGrid.TextVisible = false;
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "RolePermissionManagementView"; Size = new System.Drawing.Size(1200, 720); Load += RolePermissionManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridRoles).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewRoles).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureBar(DevExpress.XtraBars.Bar b) { b.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); b.BarAppearance.Disabled.Options.UseFont = true; b.BarAppearance.Normal.Font = b.BarAppearance.Hovered.Font = b.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); b.BarAppearance.Normal.ForeColor = b.BarAppearance.Hovered.ForeColor = b.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; b.BarAppearance.Normal.Options.UseFont = b.BarAppearance.Hovered.Options.UseFont = b.BarAppearance.Pressed.Options.UseFont = true; b.BarAppearance.Normal.Options.UseForeColor = b.BarAppearance.Hovered.Options.UseForeColor = b.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void ConfigureGrid(DevExpress.XtraGrid.Views.Grid.GridView v) { v.OptionsBehavior.Editable = false; v.OptionsSelection.EnableAppearanceFocusedCell = false; v.OptionsSelection.EnableAppearanceHotTrackedRow = DevExpress.Utils.DefaultBoolean.True; v.OptionsView.ColumnAutoWidth = false; v.OptionsView.EnableAppearanceOddRow = true; v.OptionsView.ShowAutoFilterRow = true; v.OptionsView.ShowGroupPanel = false; v.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); v.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; v.Appearance.HeaderPanel.Options.UseFont = true; v.Appearance.HeaderPanel.Options.UseForeColor = true; v.Appearance.HeaderPanel.Options.UseTextOptions = true; v.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; v.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); v.Appearance.Row.Options.UseFont = true; }
        private static void Column(DevExpress.XtraGrid.Columns.GridColumn c, string field, string caption, int width, int index) { c.FieldName = field; c.Caption = caption; c.Width = width; c.Visible = true; c.VisibleIndex = index; }
    }
}
