namespace Winform4System.Forms.SystemManagement
{
    partial class RolePermissionEditForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutTabs;
        private DevExpress.XtraTab.XtraTabControl tabControl;
        private DevExpress.XtraTab.XtraTabPage tabGeneral, tabMatrix, tabGroups, tabUsers;
        private DevExpress.XtraLayout.LayoutControl generalLayout, matrixLayout, groupsLayout, usersLayout;
        private DevExpress.XtraLayout.LayoutControlGroup generalRoot, matrixRoot, groupsRoot, usersRoot;
        private DevExpress.XtraLayout.LayoutControlItem layoutCode, layoutName, layoutSystem, layoutDescription, layoutMatrix, layoutGroups, layoutUsers;
        private DevExpress.XtraLayout.EmptySpaceItem generalBottomSpace;
        private DevExpress.XtraEditors.TextEdit txbCode, txbName;
        private DevExpress.XtraEditors.LabelControl lblSystemRole;
        private DevExpress.XtraEditors.MemoEdit memoDescription;
        private DevExpress.XtraGrid.GridControl gridMatrix, gridGroups, gridUsers;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewMatrix, gridViewGroups, gridViewUsers;
        private DevExpress.XtraGrid.Columns.GridColumn colFunctionName, colFunctionCode, colAccess, colView, colCreate, colUpdate, colDelete, colApprove, colExport, colAdmin, colGroupCode, colGroupName, colGroupActive, colUserId, colUserTW, colUserVN, colUserActive;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutTabs = new DevExpress.XtraLayout.LayoutControlItem(); tabControl = new DevExpress.XtraTab.XtraTabControl(); tabGeneral = new DevExpress.XtraTab.XtraTabPage(); tabMatrix = new DevExpress.XtraTab.XtraTabPage(); tabGroups = new DevExpress.XtraTab.XtraTabPage(); tabUsers = new DevExpress.XtraTab.XtraTabPage();
            generalLayout = new DevExpress.XtraLayout.LayoutControl(); matrixLayout = new DevExpress.XtraLayout.LayoutControl(); groupsLayout = new DevExpress.XtraLayout.LayoutControl(); usersLayout = new DevExpress.XtraLayout.LayoutControl(); generalRoot = new DevExpress.XtraLayout.LayoutControlGroup(); matrixRoot = new DevExpress.XtraLayout.LayoutControlGroup(); groupsRoot = new DevExpress.XtraLayout.LayoutControlGroup(); usersRoot = new DevExpress.XtraLayout.LayoutControlGroup(); layoutCode = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutSystem = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); layoutMatrix = new DevExpress.XtraLayout.LayoutControlItem(); layoutGroups = new DevExpress.XtraLayout.LayoutControlItem(); layoutUsers = new DevExpress.XtraLayout.LayoutControlItem(); generalBottomSpace = new DevExpress.XtraLayout.EmptySpaceItem();
            txbCode = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); lblSystemRole = new DevExpress.XtraEditors.LabelControl(); memoDescription = new DevExpress.XtraEditors.MemoEdit(); gridMatrix = new DevExpress.XtraGrid.GridControl(); gridGroups = new DevExpress.XtraGrid.GridControl(); gridUsers = new DevExpress.XtraGrid.GridControl(); gridViewMatrix = new DevExpress.XtraGrid.Views.Grid.GridView(); gridViewGroups = new DevExpress.XtraGrid.Views.Grid.GridView(); gridViewUsers = new DevExpress.XtraGrid.Views.Grid.GridView();
            colFunctionName = new DevExpress.XtraGrid.Columns.GridColumn(); colFunctionCode = new DevExpress.XtraGrid.Columns.GridColumn(); colAccess = new DevExpress.XtraGrid.Columns.GridColumn(); colView = new DevExpress.XtraGrid.Columns.GridColumn(); colCreate = new DevExpress.XtraGrid.Columns.GridColumn(); colUpdate = new DevExpress.XtraGrid.Columns.GridColumn(); colDelete = new DevExpress.XtraGrid.Columns.GridColumn(); colApprove = new DevExpress.XtraGrid.Columns.GridColumn(); colExport = new DevExpress.XtraGrid.Columns.GridColumn(); colAdmin = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupCode = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupName = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupActive = new DevExpress.XtraGrid.Columns.GridColumn(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colUserTW = new DevExpress.XtraGrid.Columns.GridColumn(); colUserVN = new DevExpress.XtraGrid.Columns.GridColumn(); colUserActive = new DevExpress.XtraGrid.Columns.GridColumn();
            BeginInitialize();

            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barTools; barManager.MaxItemId = 2;
            barTools.BarName = "角色與權限工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; BarStyle(barTools);
            btnSave.Caption = "儲存"; btnSave.Id = 0; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick;
            btnCancel.Caption = "取消"; btnCancel.Id = 1; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;

            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(tabControl); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(1200, 751);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutTabs }); Root.Size = new System.Drawing.Size(1200, 751); layoutTabs.Control = tabControl; layoutTabs.Location = new System.Drawing.Point(0, 0); layoutTabs.Size = new System.Drawing.Size(1180, 731); layoutTabs.TextVisible = false;

            tabControl.AppearancePage.Header.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); tabControl.AppearancePage.Header.ForeColor = System.Drawing.Color.Black; tabControl.AppearancePage.Header.Options.UseFont = true; tabControl.AppearancePage.Header.Options.UseForeColor = true; tabControl.AppearancePage.HeaderActive.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F, System.Drawing.FontStyle.Bold); tabControl.AppearancePage.HeaderActive.Options.UseFont = true; tabControl.Location = new System.Drawing.Point(12, 12); tabControl.SelectedTabPage = tabGeneral; tabControl.Size = new System.Drawing.Size(1176, 727); tabControl.TabPages.AddRange(new[] { tabGeneral, tabMatrix, tabGroups, tabUsers });
            ConfigureTab(tabGeneral, generalLayout, "基本資料", 1174, 686); ConfigureTab(tabMatrix, matrixLayout, "權限矩陣", 1174, 686); ConfigureTab(tabGroups, groupsLayout, "受影響群組", 1174, 686); ConfigureTab(tabUsers, usersLayout, "受影響人員", 1174, 686);

            generalLayout.Controls.AddRange(new System.Windows.Forms.Control[] { txbCode, txbName, lblSystemRole, memoDescription }); Editor(txbCode); Editor(txbName); Editor(memoDescription); lblSystemRole.Text = "系統角色：否"; lblSystemRole.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); lblSystemRole.Appearance.ForeColor = System.Drawing.Color.Black; lblSystemRole.Appearance.Options.UseFont = true; lblSystemRole.Appearance.Options.UseForeColor = true;
            ConfigureLayout(generalLayout, generalRoot, 1174, 686); generalRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, generalBottomSpace }); Item(layoutCode, txbCode, "角色代碼", 0, 0, 1154, 40); Item(layoutName, txbName, "角色名稱", 0, 40, 1154, 40); Item(layoutSystem, lblSystemRole, "", 0, 80, 1154, 40); Item(layoutDescription, memoDescription, "角色說明", 0, 120, 1154, 200); generalBottomSpace.Location = new System.Drawing.Point(0, 320); generalBottomSpace.Size = new System.Drawing.Size(1154, 346);

            ConfigureLayout(matrixLayout, matrixRoot, 1174, 686); matrixLayout.Controls.Add(gridMatrix); matrixRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutMatrix }); FullItem(layoutMatrix, gridMatrix, 1154, 666);
            gridMatrix.MainView = gridViewMatrix; gridMatrix.ViewCollection.Add(gridViewMatrix); GridStyle(gridViewMatrix, true); gridViewMatrix.ShowingEditor += gridViewMatrix_ShowingEditor; gridViewMatrix.Columns.AddRange(new[] { colFunctionName, colFunctionCode, colAccess, colView, colCreate, colUpdate, colDelete, colApprove, colExport, colAdmin }); MatrixColumn(colFunctionName, "FunctionName", "功能名稱", 220, 0, false); MatrixColumn(colFunctionCode, "FunctionCode", "功能代碼", 250, 1, false); MatrixColumn(colAccess, "Access", "存取", 75, 2, true); MatrixColumn(colView, "View", "檢視", 75, 3, true); MatrixColumn(colCreate, "Create", "新增", 75, 4, true); MatrixColumn(colUpdate, "Update", "修改", 75, 5, true); MatrixColumn(colDelete, "Delete", "刪除", 75, 6, true); MatrixColumn(colApprove, "Approve", "核准", 75, 7, true); MatrixColumn(colExport, "Export", "匯出", 75, 8, true); MatrixColumn(colAdmin, "Admin", "管理", 75, 9, true);

            ConfigureLayout(groupsLayout, groupsRoot, 1174, 686); groupsLayout.Controls.Add(gridGroups); groupsRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGroups }); FullItem(layoutGroups, gridGroups, 1154, 666);
            gridGroups.MainView = gridViewGroups; gridGroups.ViewCollection.Add(gridViewGroups); GridStyle(gridViewGroups, false); gridViewGroups.Columns.AddRange(new[] { colGroupCode, colGroupName, colGroupActive }); Column(colGroupCode, "GroupCode", "群組代碼", 260, 0); Column(colGroupName, "GroupName", "群組名稱", 360, 1); Column(colGroupActive, "IsActive", "啟用", 100, 2);

            ConfigureLayout(usersLayout, usersRoot, 1174, 686); usersLayout.Controls.Add(gridUsers); usersRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutUsers }); FullItem(layoutUsers, gridUsers, 1154, 666);
            gridUsers.MainView = gridViewUsers; gridUsers.ViewCollection.Add(gridViewUsers); GridStyle(gridViewUsers, false); gridViewUsers.Columns.AddRange(new[] { colUserId, colUserTW, colUserVN, colUserActive }); Column(colUserId, "UserId", "人員編號", 160, 0); Column(colUserTW, "DisplayNameTW", "中文姓名", 220, 1); Column(colUserVN, "DisplayNameVN", "越文姓名", 280, 2); Column(colUserActive, "IsAccountActive", "帳號啟用", 120, 3);

            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(1200, 800); MinimumSize = new System.Drawing.Size(1050, 700); StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "角色與權限"; IconOptions.Icon = Winform4System.Properties.Resources.AppIcon;
            EndInitialize();
        }

        private void BeginInitialize()
        {
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutTabs).BeginInit(); ((System.ComponentModel.ISupportInitialize)tabControl).BeginInit(); tabControl.SuspendLayout(); tabGeneral.SuspendLayout(); tabMatrix.SuspendLayout(); tabGroups.SuspendLayout(); tabUsers.SuspendLayout();
            foreach (DevExpress.XtraLayout.LayoutControl layout in new[] { generalLayout, matrixLayout, groupsLayout, usersLayout }) { ((System.ComponentModel.ISupportInitialize)layout).BeginInit(); layout.SuspendLayout(); }
            foreach (DevExpress.XtraLayout.LayoutControlGroup group in new[] { generalRoot, matrixRoot, groupsRoot, usersRoot }) ((System.ComponentModel.ISupportInitialize)group).BeginInit();
            foreach (DevExpress.XtraLayout.BaseLayoutItem item in new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, layoutMatrix, layoutGroups, layoutUsers, generalBottomSpace }) ((System.ComponentModel.ISupportInitialize)item).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txbCode.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridMatrix).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewMatrix).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridUsers).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewUsers).BeginInit(); SuspendLayout();
        }

        private void EndInitialize()
        {
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutTabs).EndInit(); ((System.ComponentModel.ISupportInitialize)tabControl).EndInit(); tabControl.ResumeLayout(false); tabGeneral.ResumeLayout(false); tabMatrix.ResumeLayout(false); tabGroups.ResumeLayout(false); tabUsers.ResumeLayout(false);
            foreach (DevExpress.XtraLayout.LayoutControl layout in new[] { generalLayout, matrixLayout, groupsLayout, usersLayout }) { ((System.ComponentModel.ISupportInitialize)layout).EndInit(); layout.ResumeLayout(false); }
            foreach (DevExpress.XtraLayout.LayoutControlGroup group in new[] { generalRoot, matrixRoot, groupsRoot, usersRoot }) ((System.ComponentModel.ISupportInitialize)group).EndInit();
            foreach (DevExpress.XtraLayout.BaseLayoutItem item in new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, layoutMatrix, layoutGroups, layoutUsers, generalBottomSpace }) ((System.ComponentModel.ISupportInitialize)item).EndInit();
            ((System.ComponentModel.ISupportInitialize)txbCode.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)gridMatrix).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewMatrix).EndInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).EndInit(); ((System.ComponentModel.ISupportInitialize)gridUsers).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewUsers).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureTab(DevExpress.XtraTab.XtraTabPage page, System.Windows.Forms.Control content, string caption, int width, int height) { page.Controls.Add(content); page.Text = caption; page.Size = new System.Drawing.Size(width, height); }
        private static void ConfigureLayout(DevExpress.XtraLayout.LayoutControl layout, DevExpress.XtraLayout.LayoutControlGroup root, int width, int height) { layout.AllowCustomization = false; layout.Dock = System.Windows.Forms.DockStyle.Fill; layout.Root = root; layout.Size = new System.Drawing.Size(width, height); root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; root.GroupBordersVisible = false; root.Size = new System.Drawing.Size(width, height); }
        private static void FullItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, int width, int height) { item.Control = control; item.Location = new System.Drawing.Point(0, 0); item.Size = new System.Drawing.Size(width, height); item.TextVisible = false; }
        private static void BarStyle(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void Editor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.ForeColor = System.Drawing.Color.Black; editor.Properties.Appearance.Options.UseFont = true; editor.Properties.Appearance.Options.UseForeColor = true; }
        private static void GridStyle(DevExpress.XtraGrid.Views.Grid.GridView view, bool editable) { view.OptionsBehavior.Editable = editable; view.OptionsSelection.EnableAppearanceFocusedCell = editable; view.OptionsView.ColumnAutoWidth = false; view.OptionsView.EnableAppearanceOddRow = true; view.OptionsView.ShowAutoFilterRow = true; view.OptionsView.ShowGroupPanel = false; view.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); view.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; view.Appearance.HeaderPanel.Options.UseFont = true; view.Appearance.HeaderPanel.Options.UseForeColor = true; view.Appearance.HeaderPanel.Options.UseTextOptions = true; view.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; view.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); view.Appearance.Row.ForeColor = System.Drawing.Color.Black; view.Appearance.Row.Options.UseFont = true; view.Appearance.Row.Options.UseForeColor = true; }
        private static void MatrixColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index, bool editable) { Column(column, field, caption, width, index); column.OptionsColumn.AllowEdit = editable; }
        private static void Column(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void Item(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string text, int x, int y, int width, int height) { item.Control = control; item.Text = text; item.Location = new System.Drawing.Point(x, y); item.Size = new System.Drawing.Size(width, height); item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.ForeColor = System.Drawing.Color.Black; item.AppearanceItemCaption.Options.UseFont = true; item.AppearanceItemCaption.Options.UseForeColor = true; item.TextSize = new System.Drawing.Size(115, 24); if (string.IsNullOrEmpty(text)) item.TextVisible = false; }
    }
}
