namespace Winform4System.Forms.SystemManagement
{
    partial class RolePermissionEditForm
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutCode, layoutName, layoutSystem, layoutDescription, layoutMatrix, layoutGroups, layoutUsers; private DevExpress.XtraEditors.TextEdit txbCode, txbName; private DevExpress.XtraEditors.LabelControl lblSystemRole; private DevExpress.XtraEditors.MemoEdit memoDescription; private DevExpress.XtraGrid.GridControl gridMatrix, gridGroups, gridUsers; private DevExpress.XtraGrid.Views.Grid.GridView gridViewMatrix, gridViewGroups, gridViewUsers; private DevExpress.XtraGrid.Columns.GridColumn colFunctionName, colFunctionCode, colAccess, colView, colCreate, colUpdate, colDelete, colApprove, colExport, colAdmin, colGroupCode, colGroupName, colGroupActive, colUserId, colUserTW, colUserVN, colUserActive;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutCode = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutSystem = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); layoutMatrix = new DevExpress.XtraLayout.LayoutControlItem(); layoutGroups = new DevExpress.XtraLayout.LayoutControlItem(); layoutUsers = new DevExpress.XtraLayout.LayoutControlItem(); txbCode = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); lblSystemRole = new DevExpress.XtraEditors.LabelControl(); memoDescription = new DevExpress.XtraEditors.MemoEdit(); gridMatrix = new DevExpress.XtraGrid.GridControl(); gridGroups = new DevExpress.XtraGrid.GridControl(); gridUsers = new DevExpress.XtraGrid.GridControl(); gridViewMatrix = new DevExpress.XtraGrid.Views.Grid.GridView(); gridViewGroups = new DevExpress.XtraGrid.Views.Grid.GridView(); gridViewUsers = new DevExpress.XtraGrid.Views.Grid.GridView(); colFunctionName = new DevExpress.XtraGrid.Columns.GridColumn(); colFunctionCode = new DevExpress.XtraGrid.Columns.GridColumn(); colAccess = new DevExpress.XtraGrid.Columns.GridColumn(); colView = new DevExpress.XtraGrid.Columns.GridColumn(); colCreate = new DevExpress.XtraGrid.Columns.GridColumn(); colUpdate = new DevExpress.XtraGrid.Columns.GridColumn(); colDelete = new DevExpress.XtraGrid.Columns.GridColumn(); colApprove = new DevExpress.XtraGrid.Columns.GridColumn(); colExport = new DevExpress.XtraGrid.Columns.GridColumn(); colAdmin = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupCode = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupName = new DevExpress.XtraGrid.Columns.GridColumn(); colGroupActive = new DevExpress.XtraGrid.Columns.GridColumn(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colUserTW = new DevExpress.XtraGrid.Columns.GridColumn(); colUserVN = new DevExpress.XtraGrid.Columns.GridColumn(); colUserActive = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridMatrix).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewMatrix).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridUsers).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewUsers).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barTools; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; BarStyle(barTools); btnSave.Caption = "儲存"; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick; btnCancel.Caption = "取消"; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Root = Root; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbCode, txbName, lblSystemRole, memoDescription, gridMatrix, gridGroups, gridUsers }); Editor(txbCode); Editor(txbName); Editor(memoDescription); lblSystemRole.Text = "系統角色：否"; lblSystemRole.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); lblSystemRole.Appearance.Options.UseFont = true;
            gridMatrix.MainView = gridViewMatrix; gridMatrix.ViewCollection.Add(gridViewMatrix); GridStyle(gridViewMatrix, true); gridViewMatrix.ShowingEditor += gridViewMatrix_ShowingEditor; gridViewMatrix.Columns.AddRange(new[] { colFunctionName, colFunctionCode, colAccess, colView, colCreate, colUpdate, colDelete, colApprove, colExport, colAdmin }); MatrixColumn(colFunctionName, "FunctionName", "功能名稱", 170, 0, false); MatrixColumn(colFunctionCode, "FunctionCode", "功能代碼", 190, 1, false); MatrixColumn(colAccess, "Access", "存取", 65, 2, true); MatrixColumn(colView, "View", "檢視", 65, 3, true); MatrixColumn(colCreate, "Create", "新增", 65, 4, true); MatrixColumn(colUpdate, "Update", "修改", 65, 5, true); MatrixColumn(colDelete, "Delete", "刪除", 65, 6, true); MatrixColumn(colApprove, "Approve", "核准", 65, 7, true); MatrixColumn(colExport, "Export", "匯出", 65, 8, true); MatrixColumn(colAdmin, "Admin", "管理", 65, 9, true);
            gridGroups.MainView = gridViewGroups; gridGroups.ViewCollection.Add(gridViewGroups); GridStyle(gridViewGroups, false); gridViewGroups.Columns.AddRange(new[] { colGroupCode, colGroupName, colGroupActive }); Column(colGroupCode, "GroupCode", "群組代碼", 180, 0); Column(colGroupName, "GroupName", "群組名稱", 220, 1); Column(colGroupActive, "IsActive", "啟用", 80, 2); gridUsers.MainView = gridViewUsers; gridUsers.ViewCollection.Add(gridViewUsers); GridStyle(gridViewUsers, false); gridViewUsers.Columns.AddRange(new[] { colUserId, colUserTW, colUserVN, colUserActive }); Column(colUserId, "UserId", "人員編號", 120, 0); Column(colUserTW, "DisplayNameTW", "中文姓名", 170, 1); Column(colUserVN, "DisplayNameVN", "越文姓名", 220, 2); Column(colUserActive, "IsAccountActive", "帳號啟用", 90, 3);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, layoutMatrix, layoutGroups, layoutUsers }); Item(layoutCode, txbCode, "角色代碼", 36); Item(layoutName, txbName, "角色名稱", 36); Item(layoutSystem, lblSystemRole, "", 36); Item(layoutDescription, memoDescription, "角色說明", 80); Item(layoutMatrix, gridMatrix, "權限矩陣", 300); Item(layoutGroups, gridGroups, "受影響群組", 150); Item(layoutUsers, gridUsers, "受影響人員", 170);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(1200, 900); MinimumSize = new System.Drawing.Size(1050, 800); StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "角色與權限"; IconOptions.Icon = Winform4System.Properties.Resources.AppIcon;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)gridMatrix).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewMatrix).EndInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).EndInit(); ((System.ComponentModel.ISupportInitialize)gridUsers).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewUsers).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void BarStyle(DevExpress.XtraBars.Bar b) { b.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); b.BarAppearance.Disabled.Options.UseFont = true; b.BarAppearance.Normal.Font = b.BarAppearance.Hovered.Font = b.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); b.BarAppearance.Normal.ForeColor = b.BarAppearance.Hovered.ForeColor = b.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; b.BarAppearance.Normal.Options.UseFont = b.BarAppearance.Hovered.Options.UseFont = b.BarAppearance.Pressed.Options.UseFont = true; }
        private static void Editor(DevExpress.XtraEditors.BaseEdit e) { e.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); e.Properties.Appearance.Options.UseFont = true; }
        private static void GridStyle(DevExpress.XtraGrid.Views.Grid.GridView v, bool editable) { v.OptionsBehavior.Editable = editable; v.OptionsSelection.EnableAppearanceFocusedCell = editable; v.OptionsView.ColumnAutoWidth = false; v.OptionsView.EnableAppearanceOddRow = true; v.OptionsView.ShowAutoFilterRow = true; v.OptionsView.ShowGroupPanel = false; v.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); v.Appearance.HeaderPanel.Options.UseFont = true; v.Appearance.HeaderPanel.Options.UseTextOptions = true; v.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; v.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); v.Appearance.Row.Options.UseFont = true; }
        private static void MatrixColumn(DevExpress.XtraGrid.Columns.GridColumn c, string field, string caption, int width, int index, bool editable) { Column(c, field, caption, width, index); c.OptionsColumn.AllowEdit = editable; }
        private static void Column(DevExpress.XtraGrid.Columns.GridColumn c, string field, string caption, int width, int index) { c.FieldName = field; c.Caption = caption; c.Width = width; c.Visible = true; c.VisibleIndex = index; }
        private static void Item(DevExpress.XtraLayout.LayoutControlItem i, System.Windows.Forms.Control c, string text, int height) { i.Control = c; i.Text = text; i.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); i.AppearanceItemCaption.Options.UseFont = true; i.TextSize = new System.Drawing.Size(115, 24); i.MinSize = new System.Drawing.Size(0, height); if (string.IsNullOrEmpty(text)) i.TextVisible = false; }
    }
}
