namespace Winform4System.Forms.SystemManagement
{
    partial class SecurityGroupEditForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutTabs;
        private DevExpress.XtraTab.XtraTabControl tabControl;
        private DevExpress.XtraTab.XtraTabPage tabGeneral, tabRoles, tabMembers;
        private DevExpress.XtraLayout.LayoutControl generalLayout;
        private DevExpress.XtraLayout.LayoutControlGroup generalRoot;
        private DevExpress.XtraLayout.LayoutControlItem layoutCode, layoutName, layoutSystem, layoutDescription;
        private DevExpress.XtraLayout.EmptySpaceItem generalBottomSpace;
        private DevExpress.XtraEditors.TextEdit txbCode, txbName;
        private DevExpress.XtraEditors.LabelControl lblSystemGroup;
        private DevExpress.XtraEditors.MemoEdit memoDescription;
        private DevExpress.XtraLayout.LayoutControl rolesLayout;
        private DevExpress.XtraLayout.LayoutControlGroup rolesRoot;
        private DevExpress.XtraLayout.LayoutControlItem layoutRoles;
        private DevExpress.XtraEditors.CheckedListBoxControl checkedRoles;
        private DevExpress.XtraLayout.LayoutControl membersLayout;
        private DevExpress.XtraLayout.LayoutControlGroup membersRoot;
        private DevExpress.XtraLayout.LayoutControlItem layoutMembers;
        private DevExpress.XtraGrid.GridControl gridMembers;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewMembers;
        private DevExpress.XtraGrid.Columns.GridColumn colUserId, colDisplayNameTW, colDisplayNameVN, colDepartment, colAccountActive, colExpiresAt;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutTabs = new DevExpress.XtraLayout.LayoutControlItem(); tabControl = new DevExpress.XtraTab.XtraTabControl(); tabGeneral = new DevExpress.XtraTab.XtraTabPage(); tabRoles = new DevExpress.XtraTab.XtraTabPage(); tabMembers = new DevExpress.XtraTab.XtraTabPage();
            generalLayout = new DevExpress.XtraLayout.LayoutControl(); generalRoot = new DevExpress.XtraLayout.LayoutControlGroup(); layoutCode = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutSystem = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); generalBottomSpace = new DevExpress.XtraLayout.EmptySpaceItem(); txbCode = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); lblSystemGroup = new DevExpress.XtraEditors.LabelControl(); memoDescription = new DevExpress.XtraEditors.MemoEdit();
            rolesLayout = new DevExpress.XtraLayout.LayoutControl(); rolesRoot = new DevExpress.XtraLayout.LayoutControlGroup(); layoutRoles = new DevExpress.XtraLayout.LayoutControlItem(); checkedRoles = new DevExpress.XtraEditors.CheckedListBoxControl();
            membersLayout = new DevExpress.XtraLayout.LayoutControl(); membersRoot = new DevExpress.XtraLayout.LayoutControlGroup(); layoutMembers = new DevExpress.XtraLayout.LayoutControlItem(); gridMembers = new DevExpress.XtraGrid.GridControl(); gridViewMembers = new DevExpress.XtraGrid.Views.Grid.GridView(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameTW = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameVN = new DevExpress.XtraGrid.Columns.GridColumn(); colDepartment = new DevExpress.XtraGrid.Columns.GridColumn(); colAccountActive = new DevExpress.XtraGrid.Columns.GridColumn(); colExpiresAt = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutTabs).BeginInit();
            ((System.ComponentModel.ISupportInitialize)tabControl).BeginInit(); tabControl.SuspendLayout(); tabGeneral.SuspendLayout(); tabRoles.SuspendLayout(); tabMembers.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)generalLayout).BeginInit(); generalLayout.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)generalRoot).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutCode).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutName).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutSystem).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutDescription).BeginInit(); ((System.ComponentModel.ISupportInitialize)generalBottomSpace).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)rolesLayout).BeginInit(); rolesLayout.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)rolesRoot).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutRoles).BeginInit(); ((System.ComponentModel.ISupportInitialize)checkedRoles).BeginInit();
            ((System.ComponentModel.ISupportInitialize)membersLayout).BeginInit(); membersLayout.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)membersRoot).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutMembers).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridMembers).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewMembers).BeginInit(); SuspendLayout();

            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barTools; barManager.MaxItemId = 2;
            barTools.BarName = "安全性群組工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true; ConfigureBarAppearance(barTools);
            btnSave.Caption = "儲存"; btnSave.Id = 0; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick;
            btnCancel.Caption = "取消"; btnCancel.Id = 1; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(960, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;

            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(tabControl); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(960, 628);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutTabs }); Root.Size = new System.Drawing.Size(960, 628);
            layoutTabs.Control = tabControl; layoutTabs.Location = new System.Drawing.Point(0, 0); layoutTabs.Size = new System.Drawing.Size(940, 608); layoutTabs.TextVisible = false;

            tabControl.AppearancePage.Header.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); tabControl.AppearancePage.Header.ForeColor = System.Drawing.Color.Black; tabControl.AppearancePage.Header.Options.UseFont = true; tabControl.AppearancePage.Header.Options.UseForeColor = true; tabControl.AppearancePage.HeaderActive.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F, System.Drawing.FontStyle.Bold); tabControl.AppearancePage.HeaderActive.Options.UseFont = true; tabControl.Location = new System.Drawing.Point(12, 12); tabControl.Name = "tabControl"; tabControl.SelectedTabPage = tabGeneral; tabControl.Size = new System.Drawing.Size(936, 604); tabControl.TabPages.AddRange(new[] { tabGeneral, tabRoles, tabMembers });
            tabGeneral.Controls.Add(generalLayout); tabGeneral.Name = "tabGeneral"; tabGeneral.Size = new System.Drawing.Size(934, 563); tabGeneral.Text = "基本資料";
            tabRoles.Controls.Add(rolesLayout); tabRoles.Name = "tabRoles"; tabRoles.Size = new System.Drawing.Size(934, 563); tabRoles.Text = "指派角色";
            tabMembers.Controls.Add(membersLayout); tabMembers.Name = "tabMembers"; tabMembers.Size = new System.Drawing.Size(934, 563); tabMembers.Text = "群組成員";

            generalLayout.AllowCustomization = false; generalLayout.Controls.AddRange(new System.Windows.Forms.Control[] { txbCode, txbName, lblSystemGroup, memoDescription }); generalLayout.Dock = System.Windows.Forms.DockStyle.Fill; generalLayout.Root = generalRoot; generalLayout.Size = new System.Drawing.Size(934, 563);
            ConfigureEditor(txbCode); ConfigureEditor(txbName); ConfigureEditor(memoDescription); lblSystemGroup.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); lblSystemGroup.Appearance.ForeColor = System.Drawing.Color.Black; lblSystemGroup.Appearance.Options.UseFont = true; lblSystemGroup.Appearance.Options.UseForeColor = true; lblSystemGroup.Text = "系統群組：否";
            generalRoot.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; generalRoot.GroupBordersVisible = false; generalRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, generalBottomSpace }); generalRoot.Size = new System.Drawing.Size(934, 563);
            ConfigureItem(layoutCode, txbCode, "群組代碼", 0, 0, 914, 40); ConfigureItem(layoutName, txbName, "群組名稱", 0, 40, 914, 40); ConfigureItem(layoutSystem, lblSystemGroup, "", 0, 80, 914, 40); ConfigureItem(layoutDescription, memoDescription, "群組說明", 0, 120, 914, 180); generalBottomSpace.Location = new System.Drawing.Point(0, 300); generalBottomSpace.Size = new System.Drawing.Size(914, 243);

            rolesLayout.AllowCustomization = false; rolesLayout.Controls.Add(checkedRoles); rolesLayout.Dock = System.Windows.Forms.DockStyle.Fill; rolesLayout.Root = rolesRoot; rolesLayout.Size = new System.Drawing.Size(934, 563); checkedRoles.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); checkedRoles.Appearance.ForeColor = System.Drawing.Color.Black; checkedRoles.Appearance.Options.UseFont = true; checkedRoles.Appearance.Options.UseForeColor = true;
            rolesRoot.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; rolesRoot.GroupBordersVisible = false; rolesRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutRoles }); rolesRoot.Size = new System.Drawing.Size(934, 563); layoutRoles.Control = checkedRoles; layoutRoles.Location = new System.Drawing.Point(0, 0); layoutRoles.Size = new System.Drawing.Size(914, 543); layoutRoles.TextVisible = false;

            membersLayout.AllowCustomization = false; membersLayout.Controls.Add(gridMembers); membersLayout.Dock = System.Windows.Forms.DockStyle.Fill; membersLayout.Root = membersRoot; membersLayout.Size = new System.Drawing.Size(934, 563);
            gridMembers.MainView = gridViewMembers; gridMembers.ViewCollection.Add(gridViewMembers); gridViewMembers.GridControl = gridMembers; ConfigureGrid(gridViewMembers); gridViewMembers.Columns.AddRange(new[] { colUserId, colDisplayNameTW, colDisplayNameVN, colDepartment, colAccountActive, colExpiresAt }); ConfigureColumn(colUserId, "UserId", "人員編號", 120, 0); ConfigureColumn(colDisplayNameTW, "DisplayNameTW", "中文姓名", 150, 1); ConfigureColumn(colDisplayNameVN, "DisplayNameVN", "越文姓名", 200, 2); ConfigureColumn(colDepartment, "DepartmentName", "部門", 180, 3); ConfigureColumn(colAccountActive, "IsAccountActive", "帳號啟用", 100, 4); ConfigureColumn(colExpiresAt, "ExpiresAt", "到期時間", 160, 5); colExpiresAt.DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime; colExpiresAt.DisplayFormat.FormatString = "yyyy/MM/dd HH:mm";
            membersRoot.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; membersRoot.GroupBordersVisible = false; membersRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutMembers }); membersRoot.Size = new System.Drawing.Size(934, 563); layoutMembers.Control = gridMembers; layoutMembers.Location = new System.Drawing.Point(0, 0); layoutMembers.Size = new System.Drawing.Size(914, 543); layoutMembers.TextVisible = false;

            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(960, 677); Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); MinimumSize = new System.Drawing.Size(850, 650); StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "安全性群組"; IconOptions.Icon = Winform4System.Properties.Resources.AppIcon;

            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutTabs).EndInit(); ((System.ComponentModel.ISupportInitialize)tabControl).EndInit(); tabControl.ResumeLayout(false); tabGeneral.ResumeLayout(false); tabRoles.ResumeLayout(false); tabMembers.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)generalLayout).EndInit(); generalLayout.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)generalRoot).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutCode).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutName).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutSystem).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutDescription).EndInit(); ((System.ComponentModel.ISupportInitialize)generalBottomSpace).EndInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)rolesLayout).EndInit(); rolesLayout.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)rolesRoot).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutRoles).EndInit(); ((System.ComponentModel.ISupportInitialize)checkedRoles).EndInit(); ((System.ComponentModel.ISupportInitialize)membersLayout).EndInit(); membersLayout.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)membersRoot).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutMembers).EndInit(); ((System.ComponentModel.ISupportInitialize)gridMembers).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewMembers).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureBarAppearance(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void ConfigureEditor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.ForeColor = System.Drawing.Color.Black; editor.Properties.Appearance.Options.UseFont = true; editor.Properties.Appearance.Options.UseForeColor = true; }
        private static void ConfigureGrid(DevExpress.XtraGrid.Views.Grid.GridView view) { view.OptionsBehavior.Editable = false; view.OptionsSelection.EnableAppearanceFocusedCell = false; view.OptionsView.ColumnAutoWidth = false; view.OptionsView.EnableAppearanceOddRow = true; view.OptionsView.ShowAutoFilterRow = true; view.OptionsView.ShowGroupPanel = false; view.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); view.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; view.Appearance.HeaderPanel.Options.UseFont = true; view.Appearance.HeaderPanel.Options.UseForeColor = true; view.Appearance.HeaderPanel.Options.UseTextOptions = true; view.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; view.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); view.Appearance.Row.ForeColor = System.Drawing.Color.Black; view.Appearance.Row.Options.UseFont = true; view.Appearance.Row.Options.UseForeColor = true; }
        private static void ConfigureItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string caption, int x, int y, int width, int height) { item.Control = control; item.Text = caption; item.Location = new System.Drawing.Point(x, y); item.Size = new System.Drawing.Size(width, height); item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.ForeColor = System.Drawing.Color.Black; item.AppearanceItemCaption.Options.UseFont = true; item.AppearanceItemCaption.Options.UseForeColor = true; item.TextSize = new System.Drawing.Size(105, 24); if (string.IsNullOrEmpty(caption)) item.TextVisible = false; }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
    }
}
