namespace Winform4System.Forms.SystemManagement
{
    partial class SecurityGroupManagementView
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnAdd, btnReload; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutGrid; private DevExpress.XtraGrid.GridControl gridGroups; private DevExpress.XtraGrid.Views.Grid.GridView gridViewGroups; private DevExpress.XtraGrid.Columns.GridColumn colGroupId, colCode, colName, colDescription, colRoleCount, colMemberCount, colSystem, colActive;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnAdd = new DevExpress.XtraBars.BarButtonItem(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); gridGroups = new DevExpress.XtraGrid.GridControl(); gridViewGroups = new DevExpress.XtraGrid.Views.Grid.GridView(); colGroupId = new DevExpress.XtraGrid.Columns.GridColumn(); colCode = new DevExpress.XtraGrid.Columns.GridColumn(); colName = new DevExpress.XtraGrid.Columns.GridColumn(); colDescription = new DevExpress.XtraGrid.Columns.GridColumn(); colRoleCount = new DevExpress.XtraGrid.Columns.GridColumn(); colMemberCount = new DevExpress.XtraGrid.Columns.GridColumn(); colSystem = new DevExpress.XtraGrid.Columns.GridColumn(); colActive = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnAdd, btnReload }); barManager.MainMenu = barTools;
            barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnAdd), new DevExpress.XtraBars.LinkPersistInfo(btnReload) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true; ConfigureBarAppearance(barTools);
            btnAdd.Caption = "新增群組"; btnAdd.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Add; btnAdd.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnAdd.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnAdd.ItemClick += btnAdd_ItemClick; btnReload.Caption = "重新載入"; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridGroups); layoutControl.Root = Root; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Size = new System.Drawing.Size(1200, 671); gridGroups.MainView = gridViewGroups; gridGroups.ViewCollection.Add(gridViewGroups); gridViewGroups.GridControl = gridGroups; ConfigureGrid(gridViewGroups); gridViewGroups.PopupMenuShowing += gridViewGroups_PopupMenuShowing;
            gridViewGroups.Columns.AddRange(new[] { colGroupId, colCode, colName, colDescription, colRoleCount, colMemberCount, colSystem, colActive }); ConfigureColumn(colGroupId, "GroupId", "識別碼", 75, 0); ConfigureColumn(colCode, "GroupCode", "群組代碼", 180, 1); ConfigureColumn(colName, "GroupName", "群組名稱", 180, 2); ConfigureColumn(colDescription, "Description", "群組說明", 280, 3); ConfigureColumn(colRoleCount, "RoleCount", "角色數", 85, 4); ConfigureColumn(colMemberCount, "MemberCount", "成員數", 85, 5); ConfigureColumn(colSystem, "IsSystemGroup", "系統群組", 90, 6); ConfigureColumn(colActive, "IsActive", "啟用", 75, 7);
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); Root.Size = new System.Drawing.Size(1200, 671); layoutGrid.Control = gridGroups; layoutGrid.TextVisible = false;
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "SecurityGroupManagementView"; Size = new System.Drawing.Size(1200, 720); Load += SecurityGroupManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridGroups).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewGroups).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureBarAppearance(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void ConfigureGrid(DevExpress.XtraGrid.Views.Grid.GridView view) { view.OptionsBehavior.Editable = false; view.OptionsSelection.EnableAppearanceFocusedCell = false; view.OptionsSelection.EnableAppearanceHotTrackedRow = DevExpress.Utils.DefaultBoolean.True; view.OptionsView.ColumnAutoWidth = false; view.OptionsView.EnableAppearanceOddRow = true; view.OptionsView.ShowAutoFilterRow = true; view.OptionsView.ShowGroupPanel = false; view.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); view.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; view.Appearance.HeaderPanel.Options.UseFont = true; view.Appearance.HeaderPanel.Options.UseForeColor = true; view.Appearance.HeaderPanel.Options.UseTextOptions = true; view.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; view.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); view.Appearance.Row.ForeColor = System.Drawing.Color.Black; view.Appearance.Row.Options.UseFont = true; view.Appearance.Row.Options.UseForeColor = true; }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
    }
}
