namespace Winform4System.Forms.SystemManagement
{
    partial class SecurityGroupEditForm
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutCode, layoutName, layoutSystem, layoutDescription, layoutRoles, layoutMembers; private DevExpress.XtraEditors.TextEdit txbCode, txbName; private DevExpress.XtraEditors.LabelControl lblSystemGroup; private DevExpress.XtraEditors.MemoEdit memoDescription; private DevExpress.XtraEditors.CheckedListBoxControl checkedRoles; private DevExpress.XtraGrid.GridControl gridMembers; private DevExpress.XtraGrid.Views.Grid.GridView gridViewMembers; private DevExpress.XtraGrid.Columns.GridColumn colUserId, colDisplayNameTW, colDisplayNameVN, colDepartment, colAccountActive, colExpiresAt;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutCode = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutSystem = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); layoutRoles = new DevExpress.XtraLayout.LayoutControlItem(); layoutMembers = new DevExpress.XtraLayout.LayoutControlItem(); txbCode = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); lblSystemGroup = new DevExpress.XtraEditors.LabelControl(); memoDescription = new DevExpress.XtraEditors.MemoEdit(); checkedRoles = new DevExpress.XtraEditors.CheckedListBoxControl(); gridMembers = new DevExpress.XtraGrid.GridControl(); gridViewMembers = new DevExpress.XtraGrid.Views.Grid.GridView(); colUserId = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameTW = new DevExpress.XtraGrid.Columns.GridColumn(); colDisplayNameVN = new DevExpress.XtraGrid.Columns.GridColumn(); colDepartment = new DevExpress.XtraGrid.Columns.GridColumn(); colAccountActive = new DevExpress.XtraGrid.Columns.GridColumn(); colExpiresAt = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)checkedRoles).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridMembers).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewMembers).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barTools; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.MultiLine = true; barTools.OptionsBar.UseWholeRow = true; ConfigureBarAppearance(barTools);
            btnSave.Caption = "儲存"; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick; btnCancel.Caption = "取消"; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(960, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.AllowCustomization = false; layoutControl.Root = Root; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbCode, txbName, lblSystemGroup, memoDescription, checkedRoles, gridMembers });
            ConfigureEditor(txbCode); ConfigureEditor(txbName); ConfigureEditor(memoDescription); checkedRoles.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); checkedRoles.Appearance.ForeColor = System.Drawing.Color.Black; checkedRoles.Appearance.Options.UseFont = true; checkedRoles.Appearance.Options.UseForeColor = true; lblSystemGroup.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); lblSystemGroup.Appearance.ForeColor = System.Drawing.Color.Black; lblSystemGroup.Appearance.Options.UseFont = true; lblSystemGroup.Appearance.Options.UseForeColor = true; lblSystemGroup.Text = "系統群組：否";
            gridMembers.MainView = gridViewMembers; gridMembers.ViewCollection.Add(gridViewMembers); gridViewMembers.GridControl = gridMembers; ConfigureGrid(gridViewMembers); gridViewMembers.Columns.AddRange(new[] { colUserId, colDisplayNameTW, colDisplayNameVN, colDepartment, colAccountActive, colExpiresAt }); ConfigureColumn(colUserId, "UserId", "人員編號", 110, 0); ConfigureColumn(colDisplayNameTW, "DisplayNameTW", "中文姓名", 140, 1); ConfigureColumn(colDisplayNameVN, "DisplayNameVN", "越文姓名", 180, 2); ConfigureColumn(colDepartment, "DepartmentName", "部門", 140, 3); ConfigureColumn(colAccountActive, "IsAccountActive", "帳號啟用", 90, 4); ConfigureColumn(colExpiresAt, "ExpiresAt", "到期時間", 140, 5); colExpiresAt.DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime; colExpiresAt.DisplayFormat.FormatString = "yyyy/MM/dd HH:mm";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutCode, layoutName, layoutSystem, layoutDescription, layoutRoles, layoutMembers }); ConfigureItem(layoutCode, txbCode, "群組代碼", 36); ConfigureItem(layoutName, txbName, "群組名稱", 36); ConfigureItem(layoutSystem, lblSystemGroup, "", 36); ConfigureItem(layoutDescription, memoDescription, "群組說明", 90); ConfigureItem(layoutRoles, checkedRoles, "指派角色", 180); ConfigureItem(layoutMembers, gridMembers, "群組成員", 250); Root.Size = new System.Drawing.Size(960, 628);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(960, 677); Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); MinimumSize = new System.Drawing.Size(850, 650); StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "安全性群組"; IconOptions.Icon = Winform4System.Properties.Resources.AppIcon;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)txbCode.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)checkedRoles).EndInit(); ((System.ComponentModel.ISupportInitialize)gridMembers).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewMembers).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureBarAppearance(DevExpress.XtraBars.Bar bar) { bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Normal.Font = bar.BarAppearance.Hovered.Font = bar.BarAppearance.Pressed.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Normal.ForeColor = bar.BarAppearance.Hovered.ForeColor = bar.BarAppearance.Pressed.ForeColor = System.Drawing.Color.Black; bar.BarAppearance.Normal.Options.UseFont = bar.BarAppearance.Hovered.Options.UseFont = bar.BarAppearance.Pressed.Options.UseFont = true; bar.BarAppearance.Normal.Options.UseForeColor = bar.BarAppearance.Hovered.Options.UseForeColor = bar.BarAppearance.Pressed.Options.UseForeColor = true; }
        private static void ConfigureEditor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.ForeColor = System.Drawing.Color.Black; editor.Properties.Appearance.Options.UseFont = true; editor.Properties.Appearance.Options.UseForeColor = true; }
        private static void ConfigureGrid(DevExpress.XtraGrid.Views.Grid.GridView view) { view.OptionsBehavior.Editable = false; view.OptionsSelection.EnableAppearanceFocusedCell = false; view.OptionsView.ColumnAutoWidth = false; view.OptionsView.EnableAppearanceOddRow = true; view.OptionsView.ShowAutoFilterRow = true; view.OptionsView.ShowGroupPanel = false; view.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); view.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black; view.Appearance.HeaderPanel.Options.UseFont = true; view.Appearance.HeaderPanel.Options.UseForeColor = true; view.Appearance.HeaderPanel.Options.UseTextOptions = true; view.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; view.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); view.Appearance.Row.ForeColor = System.Drawing.Color.Black; view.Appearance.Row.Options.UseFont = true; view.Appearance.Row.Options.UseForeColor = true; }
        private static void ConfigureItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string caption, int height) { item.Control = control; item.Text = caption; item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.ForeColor = System.Drawing.Color.Black; item.AppearanceItemCaption.Options.UseFont = true; item.AppearanceItemCaption.Options.UseForeColor = true; item.TextSize = new System.Drawing.Size(105, 24); item.MinSize = new System.Drawing.Size(0, height); if (string.IsNullOrEmpty(caption)) item.TextVisible = false; }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
    }
}
