namespace Winform4System.Forms.SystemManagement
{
    partial class SystemSettingManagementView
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager;
        private DevExpress.XtraBars.Bar barTools;
        private DevExpress.XtraBars.BarButtonItem btnReload;
        private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlItem layoutGrid;
        private DevExpress.XtraGrid.GridControl gridSettings;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewSettings;
        private DevExpress.XtraGrid.Columns.GridColumn colName, colKey, colValue, colType, colDescription, colUpdatedBy, colUpdatedAt;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); gridSettings = new DevExpress.XtraGrid.GridControl(); gridViewSettings = new DevExpress.XtraGrid.Views.Grid.GridView(); colName = new DevExpress.XtraGrid.Columns.GridColumn(); colKey = new DevExpress.XtraGrid.Columns.GridColumn(); colValue = new DevExpress.XtraGrid.Columns.GridColumn(); colType = new DevExpress.XtraGrid.Columns.GridColumn(); colDescription = new DevExpress.XtraGrid.Columns.GridColumn(); colUpdatedBy = new DevExpress.XtraGrid.Columns.GridColumn(); colUpdatedAt = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridSettings).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewSettings).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnReload }); barManager.MainMenu = barTools; barManager.MaxItemId = 1; barTools.BarName = "系統參數工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.Add(new DevExpress.XtraBars.LinkPersistInfo(btnReload)); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; ConfigureBarFont(barTools);
            btnReload.Caption = "重新載入"; btnReload.Id = 0; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridSettings); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(1200, 671); gridSettings.Location = new System.Drawing.Point(12, 12); gridSettings.MainView = gridViewSettings; gridSettings.Size = new System.Drawing.Size(1176, 647); gridSettings.ViewCollection.Add(gridViewSettings);
            gridViewSettings.GridControl = gridSettings; gridViewSettings.OptionsBehavior.Editable = false; gridViewSettings.OptionsSelection.EnableAppearanceFocusedCell = false; gridViewSettings.OptionsView.ShowAutoFilterRow = true; gridViewSettings.OptionsView.ShowGroupPanel = false; gridViewSettings.OptionsView.ColumnAutoWidth = false; gridViewSettings.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); gridViewSettings.Appearance.HeaderPanel.Options.UseFont = true; gridViewSettings.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; gridViewSettings.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); gridViewSettings.Appearance.Row.Options.UseFont = true; gridViewSettings.PopupMenuShowing += gridViewSettings_PopupMenuShowing;
            gridViewSettings.Columns.AddRange(new[] { colName, colKey, colValue, colType, colDescription, colUpdatedBy, colUpdatedAt }); ConfigureColumn(colName, "DisplayName", "參數名稱", 220, 0); ConfigureColumn(colKey, "SettingKey", "參數代碼", 230, 1); ConfigureColumn(colValue, "SettingValueDisplay", "目前值", 250, 2); ConfigureColumn(colType, "ValueTypeDisplay", "類型", 90, 3); ConfigureColumn(colDescription, "Description", "說明", 360, 4); ConfigureColumn(colUpdatedBy, "UpdatedByUserId", "更新者", 120, 5); ConfigureColumn(colUpdatedAt, "UpdatedAt", "更新時間", 160, 6); colUpdatedAt.DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime; colUpdatedAt.DisplayFormat.FormatString = "yyyy/MM/dd HH:mm:ss";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); Root.Size = new System.Drawing.Size(1200, 671); layoutGrid.Control = gridSettings; layoutGrid.TextVisible = false; layoutGrid.Size = new System.Drawing.Size(1180, 651);
            Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "SystemSettingManagementView"; Size = new System.Drawing.Size(1200, 720); Load += SystemSettingManagementView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridSettings).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewSettings).EndInit(); ResumeLayout(false); PerformLayout();
        }

        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
