namespace Winform4System.Forms.SystemManagement
{
    partial class SystemSettingEditForm
    {
        private System.ComponentModel.IContainer components;
        private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barCommands; private DevExpress.XtraBars.BarButtonItem btnSave, btnCancel; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight;
        private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraEditors.TextEdit txbKey, txbName, txbTextValue; private DevExpress.XtraEditors.MemoEdit memoDescription; private DevExpress.XtraEditors.SpinEdit spinIntegerValue; private DevExpress.XtraEditors.CheckEdit chkBooleanValue; private DevExpress.XtraLayout.LayoutControlItem layoutKey, layoutName, layoutDescription, layoutTextValue, layoutIntegerValue, layoutBooleanValue; private DevExpress.XtraLayout.EmptySpaceItem emptyBottom;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barCommands = new DevExpress.XtraBars.Bar(); btnSave = new DevExpress.XtraBars.BarButtonItem(); btnCancel = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); txbKey = new DevExpress.XtraEditors.TextEdit(); txbName = new DevExpress.XtraEditors.TextEdit(); txbTextValue = new DevExpress.XtraEditors.TextEdit(); memoDescription = new DevExpress.XtraEditors.MemoEdit(); spinIntegerValue = new DevExpress.XtraEditors.SpinEdit(); chkBooleanValue = new DevExpress.XtraEditors.CheckEdit(); layoutKey = new DevExpress.XtraLayout.LayoutControlItem(); layoutName = new DevExpress.XtraLayout.LayoutControlItem(); layoutDescription = new DevExpress.XtraLayout.LayoutControlItem(); layoutTextValue = new DevExpress.XtraLayout.LayoutControlItem(); layoutIntegerValue = new DevExpress.XtraLayout.LayoutControlItem(); layoutBooleanValue = new DevExpress.XtraLayout.LayoutControlItem(); emptyBottom = new DevExpress.XtraLayout.EmptySpaceItem();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbKey.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)txbTextValue.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)spinIntegerValue.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)chkBooleanValue.Properties).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barCommands }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnSave, btnCancel }); barManager.MainMenu = barCommands; barManager.MaxItemId = 2; barCommands.BarName = "參數編輯工具列"; barCommands.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barCommands.LinksPersistInfo.AddRange(new[] { new DevExpress.XtraBars.LinkPersistInfo(btnSave), new DevExpress.XtraBars.LinkPersistInfo(btnCancel) }); barCommands.OptionsBar.AllowQuickCustomization = false; barCommands.OptionsBar.DrawDragBorder = false; barCommands.OptionsBar.UseWholeRow = true; ConfigureBarFont(barCommands);
            btnSave.Caption = "儲存"; btnSave.Id = 0; btnSave.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Confirm; btnSave.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnSave.ItemClick += btnSave_ItemClick; btnCancel.Caption = "取消"; btnCancel.Id = 1; btnCancel.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Cancel; btnCancel.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnCancel.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnCancel.ItemClick += btnCancel_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(760, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.AddRange(new System.Windows.Forms.Control[] { txbKey, txbName, memoDescription, txbTextValue, spinIntegerValue, chkBooleanValue }); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(760, 351);
            ConfigureEditor(txbKey); ConfigureEditor(txbName); ConfigureEditor(txbTextValue); ConfigureEditor(memoDescription); ConfigureEditor(spinIntegerValue); ConfigureEditor(chkBooleanValue); txbKey.Properties.ReadOnly = true; txbName.Properties.ReadOnly = true; memoDescription.Properties.ReadOnly = true; spinIntegerValue.Properties.IsFloatValue = false; spinIntegerValue.Properties.MaskSettings.Set("mask", "d"); chkBooleanValue.Properties.Caption = "啟用";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutKey, layoutName, layoutDescription, layoutTextValue, layoutIntegerValue, layoutBooleanValue, emptyBottom }); Root.Size = new System.Drawing.Size(760, 351);
            ConfigureLayoutItem(layoutKey, txbKey, "參數代碼", 0, 0, 740, 40); ConfigureLayoutItem(layoutName, txbName, "參數名稱", 0, 40, 740, 40); ConfigureLayoutItem(layoutDescription, memoDescription, "說明", 0, 80, 740, 90); ConfigureLayoutItem(layoutTextValue, txbTextValue, "參數值", 0, 170, 740, 40); ConfigureLayoutItem(layoutIntegerValue, spinIntegerValue, "參數值", 0, 170, 740, 40); ConfigureLayoutItem(layoutBooleanValue, chkBooleanValue, "參數值", 0, 170, 740, 40); emptyBottom.Location = new System.Drawing.Point(0, 210); emptyBottom.Size = new System.Drawing.Size(740, 121);
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; ClientSize = new System.Drawing.Size(760, 400); Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog; IconOptions.Icon = global::Winform4System.Properties.Resources.AppIcon; MaximizeBox = false; MinimizeBox = false; Name = "SystemSettingEditForm"; StartPosition = System.Windows.Forms.FormStartPosition.CenterParent; Text = "編輯系統參數";
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)txbKey.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbName.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)txbTextValue.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)memoDescription.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)spinIntegerValue.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)chkBooleanValue.Properties).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureEditor(DevExpress.XtraEditors.BaseEdit editor) { editor.Properties.Appearance.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); editor.Properties.Appearance.Options.UseFont = true; }
        private static void ConfigureLayoutItem(DevExpress.XtraLayout.LayoutControlItem item, System.Windows.Forms.Control control, string caption, int x, int y, int width, int height) { item.Control = control; item.Text = caption; item.Location = new System.Drawing.Point(x, y); item.Size = new System.Drawing.Size(width, height); item.TextSize = new System.Drawing.Size(95, 24); item.AppearanceItemCaption.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); item.AppearanceItemCaption.Options.UseFont = true; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
