namespace Winform4System.Forms.SystemManagement
{
    partial class SystemHealthView
    {
        private System.ComponentModel.IContainer components; private DevExpress.XtraBars.BarManager barManager; private DevExpress.XtraBars.Bar barTools; private DevExpress.XtraBars.BarButtonItem btnReload; private DevExpress.XtraBars.BarDockControl barDockControlTop, barDockControlBottom, barDockControlLeft, barDockControlRight; private DevExpress.XtraLayout.LayoutControl layoutControl; private DevExpress.XtraLayout.LayoutControlGroup Root; private DevExpress.XtraLayout.LayoutControlItem layoutGrid; private DevExpress.XtraGrid.GridControl gridHealth; private DevExpress.XtraGrid.Views.Grid.GridView gridViewHealth; private DevExpress.XtraGrid.Columns.GridColumn colCategory, colCheckName, colState, colDetail, colCheckedAt;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); barManager = new DevExpress.XtraBars.BarManager(components); barTools = new DevExpress.XtraBars.Bar(); btnReload = new DevExpress.XtraBars.BarButtonItem(); barDockControlTop = new DevExpress.XtraBars.BarDockControl(); barDockControlBottom = new DevExpress.XtraBars.BarDockControl(); barDockControlLeft = new DevExpress.XtraBars.BarDockControl(); barDockControlRight = new DevExpress.XtraBars.BarDockControl(); layoutControl = new DevExpress.XtraLayout.LayoutControl(); Root = new DevExpress.XtraLayout.LayoutControlGroup(); layoutGrid = new DevExpress.XtraLayout.LayoutControlItem(); gridHealth = new DevExpress.XtraGrid.GridControl(); gridViewHealth = new DevExpress.XtraGrid.Views.Grid.GridView(); colCategory = new DevExpress.XtraGrid.Columns.GridColumn(); colCheckName = new DevExpress.XtraGrid.Columns.GridColumn(); colState = new DevExpress.XtraGrid.Columns.GridColumn(); colDetail = new DevExpress.XtraGrid.Columns.GridColumn(); colCheckedAt = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)barManager).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).BeginInit(); layoutControl.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)Root).BeginInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridHealth).BeginInit(); ((System.ComponentModel.ISupportInitialize)gridViewHealth).BeginInit(); SuspendLayout();
            barManager.Bars.AddRange(new[] { barTools }); barManager.DockControls.Add(barDockControlTop); barManager.DockControls.Add(barDockControlBottom); barManager.DockControls.Add(barDockControlLeft); barManager.DockControls.Add(barDockControlRight); barManager.Form = this; barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] { btnReload }); barManager.MainMenu = barTools; barManager.MaxItemId = 1; barTools.BarName = "系統狀態工具列"; barTools.DockStyle = DevExpress.XtraBars.BarDockStyle.Top; barTools.LinksPersistInfo.Add(new DevExpress.XtraBars.LinkPersistInfo(btnReload)); barTools.OptionsBar.AllowQuickCustomization = false; barTools.OptionsBar.DrawDragBorder = false; barTools.OptionsBar.UseWholeRow = true; ConfigureBarFont(barTools); btnReload.Caption = "重新檢查"; btnReload.Id = 0; btnReload.ImageOptions.SvgImage = Winform4System.Helpers.SvgIconCatalog.Refresh; btnReload.ImageOptions.SvgImageSize = new System.Drawing.Size(32, 32); btnReload.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph; btnReload.ItemClick += btnReload_ItemClick;
            barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top; barDockControlTop.Manager = barManager; barDockControlTop.Size = new System.Drawing.Size(1200, 49); barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom; barDockControlBottom.Manager = barManager; barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left; barDockControlLeft.Manager = barManager; barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right; barDockControlRight.Manager = barManager;
            layoutControl.AllowCustomization = false; layoutControl.Controls.Add(gridHealth); layoutControl.Dock = System.Windows.Forms.DockStyle.Fill; layoutControl.Location = new System.Drawing.Point(0, 49); layoutControl.Root = Root; layoutControl.Size = new System.Drawing.Size(1200, 671); gridHealth.Location = new System.Drawing.Point(12, 12); gridHealth.MainView = gridViewHealth; gridHealth.Size = new System.Drawing.Size(1176, 647); gridHealth.ViewCollection.Add(gridViewHealth); gridViewHealth.GridControl = gridHealth; gridViewHealth.OptionsBehavior.Editable = false; gridViewHealth.OptionsSelection.EnableAppearanceFocusedCell = false; gridViewHealth.OptionsView.ShowAutoFilterRow = true; gridViewHealth.OptionsView.ShowGroupPanel = false; gridViewHealth.OptionsView.ColumnAutoWidth = false; gridViewHealth.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); gridViewHealth.Appearance.HeaderPanel.Options.UseFont = true; gridViewHealth.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center; gridViewHealth.Appearance.Row.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); gridViewHealth.Appearance.Row.Options.UseFont = true; gridViewHealth.RowStyle += gridViewHealth_RowStyle;
            gridViewHealth.Columns.AddRange(new[] { colCategory, colCheckName, colState, colDetail, colCheckedAt }); ConfigureColumn(colCategory, "Category", "類別", 120, 0); ConfigureColumn(colCheckName, "CheckName", "檢查項目", 220, 1); ConfigureColumn(colState, "StateDisplay", "狀態", 100, 2); ConfigureColumn(colDetail, "Detail", "詳細資訊", 600, 3); ConfigureColumn(colCheckedAt, "CheckedAt", "檢查時間", 170, 4); colCheckedAt.DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime; colCheckedAt.DisplayFormat.FormatString = "yyyy/MM/dd HH:mm:ss";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True; Root.GroupBordersVisible = false; Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { layoutGrid }); Root.Size = new System.Drawing.Size(1200, 671); layoutGrid.Control = gridHealth; layoutGrid.TextVisible = false; layoutGrid.Size = new System.Drawing.Size(1180, 651); Controls.Add(layoutControl); Controls.Add(barDockControlLeft); Controls.Add(barDockControlRight); Controls.Add(barDockControlBottom); Controls.Add(barDockControlTop); AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F); AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; Name = "SystemHealthView"; Size = new System.Drawing.Size(1200, 720); Load += SystemHealthView_Load;
            ((System.ComponentModel.ISupportInitialize)barManager).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutControl).EndInit(); layoutControl.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)Root).EndInit(); ((System.ComponentModel.ISupportInitialize)layoutGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)gridHealth).EndInit(); ((System.ComponentModel.ISupportInitialize)gridViewHealth).EndInit(); ResumeLayout(false); PerformLayout();
        }
        private static void ConfigureColumn(DevExpress.XtraGrid.Columns.GridColumn column, string field, string caption, int width, int index) { column.FieldName = field; column.Caption = caption; column.Width = width; column.Visible = true; column.VisibleIndex = index; }
        private static void ConfigureBarFont(DevExpress.XtraBars.Bar bar) { var font = new System.Drawing.Font("Microsoft JhengHei UI", 14.25F); bar.BarAppearance.Disabled.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F); bar.BarAppearance.Disabled.Options.UseFont = true; bar.BarAppearance.Hovered.Font = font; bar.BarAppearance.Hovered.Options.UseFont = true; bar.BarAppearance.Normal.Font = font; bar.BarAppearance.Normal.Options.UseFont = true; bar.BarAppearance.Pressed.Font = font; bar.BarAppearance.Pressed.Options.UseFont = true; }
    }
}
