//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform4System.DataAccess.Entities.SpareParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartInspectionItem
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public int MaterialId { get; set; }
        public double InitialQuantity { get; set; }
        public Nullable<double> ActualQuantity { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Description { get; set; }
    }
}

