//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform4System.DataAccess.Entities.SpareParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartDepartment
    {
        public string Id { get; set; }
        public Nullable<int> IdChild { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameVN { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<int> AuthorizedHeadcount { get; set; }
        public bool IsActive { get; set; }
    }
}

